### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#114]
Originally reported by: **Christoph Reiter (Bitbucket: [lazka](http://bitbucket.org/lazka), GitHub: [lazka](http://github.com/lazka))**

---

_From [emergebz...@googlemail.com](https://code.google.com/u/109505409423842187251/) on July 15, 2012 18:05:10_

```
Because mutagen is licensed under the terms of GNU GPL v2, it is impossible to use the library from any non-GPL project. Please close this bug as invalid if this is intended, otherwise consider to change the license to a less restrictive one (maybe LGPL or even BSD/MIT).
```

_Original issue: http://code.google.com/p/mutagen/issues/detail?id=114_

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/114

**Comment by rnixx** [comment]
@lazka

Hi,

Ad invalid status of this issue. Is there no way to get consensus over the involved contributors to switch to a more liberal license? What's the expected benefit with sticking to GPL2 for a library (compared to a full functional application) over using LGPL e.g.?

Sorry to annoy you again with this.

Regards

**Comment by lazka** [comment]
Regarding licenses, we are currently trying to move from GPLv2 to GPLv2+,  but not sure if that will work out.

What's the expected benefit of LGPL for us?

**Comment by rnixx** [comment]
While it's totally adequate to license full functional applications under the GPL, it seems that liberal licensed libraries benefit it the end due to a broader user base. It's more likely that issues and patches are contributed back even if the lib is used in non FOSS applications, than an entire application gets open sourced because of a single library license. In such a case it's more likely that decision makers move over to another library or write it's own.

So I think that LGPL (or even more liberal) is in general the better choice for libraries than GPL, and LGPL prescribes that changes/improvements must be published anyway.

Your view on this topic may vary though ;)

Regards

**Comment by rnixx** [comment]
@lazka 

I'd be interested in your point of view ;)

Regards

**Comment by lazka** [comment]
> While it's totally adequate to license full functional applications under the GPL, it seems that liberal licensed libraries benefit it the end due to a broader user base. It's more likely that issues and patches are contributed back even if the lib is used in non FOSS applications, than an entire application gets open sourced because of a single library license. In such a case it's more likely that decision makers move over to another library or write it's own.

I agree that it might have a positive effect for mutagen. On the other hand nobody has written a similar non-GPL library in the last 10 years (or is there one?) and mutagen is used by some companies on the server side which I don't think resulted in many contributions and they usually can't provide files by customers, which would be vital for debugging. Also, this might be a bit far fetched, but currently mutagen being GPL also gives its free software users an advantage over potential non-free ones.

Although for the lack of contribution part I'm likely responsible as well, as I'm not that active in guiding/reviewing contributions. It's a bit easier now with GitHub etc.

> So I think that LGPL (or even more liberal) is in general the better choice for libraries than GPL, and LGPL prescribes that changes/improvements must be published anyway.
>
> Your view on this topic may vary though ;)

I thought about including LGPL when doing the relicensing in #291, but decided against it because I mostly wanted GPLv3/Apache compat and I didn't have a good argument for LGPL.

Maybe @MichaelUrman @joewreschnig have something to add...

**Comment by joewreschnig** [comment]
I don't generally like liberal licensing, and wouldn't agree to use use the LGPL for Mutagen. I've also managed to go the better part of a decade without a software licensing debate, and I'd like to keep it that way.

**Comment by lazka** [comment]
That settles it then. Thanks for chiming in!

**Comment by rnixx** [comment]
@lazka 

> On the other hand nobody has written a similar non-GPL library

http://taglib.org/ is LGPL/MPL, it's C++ and there exists python bindings IIRC.

Thanks for your patience

**Comment by lazka** [comment]
pytaglib is GPLv3

**Comment by rnixx** [comment]
True. In the end it may be worth writing another lib with taglib python bindings. All I need is to extract album art from songs in the end, not sure yet what the solution will finally look like.

**Comment by MichaelUrman** [comment]
I would say that the word "better" is useless on its own. To anchor its meaning, it has to be about better for some purpose or purposes. It's possible that a more permissive license may allow for more contributions, and it's possible that more contributions would be beneficial. When one's measuring stick is whether the software is free, then those possibilities are simply irrelevant. When one measures by realistic potential for use, then copyleft wins are irrelevant.

Regardless, I also would not agree to relicensing under the Lesser GPL.
