### ISSUE TITLE
Support for DSD and DFF audio files

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#155]
Originally reported by: **Christoph Reiter (Bitbucket: [lazka](http://bitbucket.org/lazka), GitHub: [lazka](http://github.com/lazka))**

---

_From [audiom...@gmail.com](https://code.google.com/u/100235480947155006868/) on June 22, 2013 04:54:33_

```
With the increasing avsailability of Direct Stream Digital Audio (DSD) content are there any plans to add support to the format in mutagen?
```

_Original issue: http://code.google.com/p/mutagen/issues/detail?id=155_

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/155

**Comment by audiomuze** [comment]
if it's so bloody trivial make the enhancement and release it or stop maintaining Mutagen and hand it to someone that'll make the effort to keep it current and relevant.

**Comment by lazka** [comment]
In case you are referring to the "trivial" label, this is an artifact of the recent bitbucket->github move. The default priority level "trivial" on bitbucket was mapped to this label on github.

**Comment by audiomuze** [comment]
You were first asked to consider this on June 22, 2013, its now almost 3 years down the road, do you have any intention of incorporating support for DFF files?

**Comment by lazka** [comment]
It depends on some changes to our ID3 code which is also needed for RIFF and AIFF. Once that is done it should be easy to add.

Btw after looking at the file formats involved, there are mentions in this issue of dsf, dff and dsd. Afaics only .dsf is a file format supporting tags. Do you mean .dsf or .dff files?

To answer your question, I'm not planing to work on this in the near future, but I'm not against supporting it in mutagen.

**Comment by audiomuze** [comment]
dff supports tags, dsf doesn't, both a varieties of DSD.

**Comment by ThomasZett** [comment]
Actually it is the other way. DSF is the Sony Spec, it supports ID3 tags.

As a C++ programmer I would need quite some help in adding dsf.
How well "decoupled" are ID3 and MP3 ?

**Comment by phw** [comment]
Proposed patch for DSDIFF (DFF) file support: #473
