### ISSUE TITLE
Support for memory files

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#255]
Originally reported by: **Chirica Gheorghe (Bitbucket: [geodroid](http://bitbucket.org/geodroid), GitHub: [geodroid](http://github.com/geodroid))**

----------------------------------------

Hi.

Currently I see that you only support reading files from disk. Are there any plans to support reading memory files(via StringIO as example) ? Currently I want to use it on GAE but we can't write files there and I want to modify the metadata. Can you guide me what needs to be change(places to look) to achieve this? 

Thx!

----------------------------------------
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/255

**Comment by caoimhghin** [comment]
Hi, I see this is closed but I didn't see a commit. Was support added through an interface to pass in a buffer instead of a filename?

**Comment by lazka** [comment]
This is already tracked in #1, github sadly has no way to mark duplicates besides closing and referencing the other issue.

**Comment by lazka** [comment]
This is now fixed in master
