### ISSUE TITLE
easyMP3 doesn't seem to work on certain files only

### ISSUE THREAD

**Issue by smintheu** [quodlibet/mutagen#258]
Warning - I'm new to python. Apologies in advance if I missed something. 

I wrote some code which creates tags based on the filename. It seems to work fine for 99% of my files, but about 1% just have their tags dropped. I can add tags manually, but when I run my script on them, they disappear. I've attached a file that doesn't seem to work (zipped). 
[Cantus - Trink, Trink, Bruderlein Trink.zip](https://github.com/quodlibet/mutagen/files/263055/Cantus.-.Trink.Trink.Bruderlein.Trink.zip)

Thanks!

Relevant code:

```
...
tmp     = re.split('\s\-\s', filename)
n = 0
while (n < len(tmp)):
    if n == 0:
        artist   = tmp[n]
    if n == 1:
        song    = tmp[n]
        song    = re.sub("(\.mp3)|(m4a)", '', song) 
    n = n+1
if n == 1:
    print("something happened. Wrongly formattted filename "+filename)
artist  = tmp[0]
song    = tmp[1]
album   = 'Songs'
track   = ''
...

completeFile = os.path.join(name, filename)
try:
    tagFile = EasyID3(completeFile)
except mutagen.id3.ID3NoHeaderError:
    tagFile = mutagen.File(completeFile, easy=True)
    
try:
    tagFile.add_tags(ID3=EasyID3)                
except:
    #print(completeFile+" has tags")
    flag = 0
#add tags                
tagFile["title"] = song
tagFile["tracknumber"] = track
tagFile["artist"] = artist
tagFile["album"] = album
try:                     
    tagFile.save()
except:
    print("could not save file "+completeFile)
```

**Comment by lazka** [comment]
Thanks. I can't reproduce here using the following:

```
from mutagen.mp3 import EasyMP3

mp3 = EasyMP3("a.mp3")
mp3["title"] = "some_title"
mp3["tracknumber"] = "some_tracknumber"
mp3["artist"] = "some_artist"
mp3["album"] = "some_album"
mp3.save()
```

Maybe I'm missing something.. please try to provide a minimal example which fails for you or doesn't work as expected.

**Comment by smintheu** [comment]
Thanks for looking into this.

If I run the following code on the file in attachment, the code runs,
doesn't throw any errors, but the mp3 still has no tags. Does it work on
the file in attachment if you run it on your system??

FYI Winows 10, python 3.5.1

from mutagen.mp3 import EasyMP3

mp3 = EasyMP3("C:\\tmp\\Cantus - Trink, Trink, Bruderlein Trink.mp3")
mp3["title"] = "some_title"
mp3["tracknumber"] = "some_tracknumber"
mp3["artist"] = "some_artist"
mp3["album"] = "some_album"
mp3.save()

On Fri, May 13, 2016 at 12:51 PM, Christoph Reiter <notifications@github.com

**Comment by lazka** [comment]
> Does it work on the file in attachment if you run it on your system??

Yes. I've tried with both python2.7 and 3.5.

What are you using to see if the tags are there after using mutagen?

**Comment by smintheu** [comment]
Ah, I was checking in an explorer window, and in the file properties ->
details. I went to check now, with a tool called TagScanner, and it can see
the tags. Do you have any idea why the tags don't show up in windows
explorer / windows explorer file properties? I mean, what sets it apart
from other files?

Thanks again!

**Comment by lazka** [comment]
> Ah, I was checking in an explorer window, and in the file properties -> details.

Windows (Explorer and the Media Player) does not support id3v2.4 fully. mutagen by default writes id3v2.4 tags and the easy variants of ID3/MP3 don't support id3v2.3, see #188.

**Comment by smintheu** [comment]
I see. thanks a lot for clearing this out!

**Comment by lazka** [comment]
#188 is fixed now
