### ISSUE TITLE
FLAC METADATA_BLOCK_PICTURE is not added correctly

### ISSUE THREAD

**Issue by tmose1106** [quodlibet/mutagen#259]
I have been trying to add album art to my FLAC files using Mutagen, and it never works out. I am using a slightly modified script of the write example in the Mutagen documentation, and to say the least, I am frustrated by how something that is on the front page of the documentation does not work properly. Here are two screen shots comparing two files. The first had a picture added using metaflac, the FLAC cli tagging tool. The second is of one tagged with the modified version of the example in the documentation: 
EXHIBIT A:
![1465951104](https://cloud.githubusercontent.com/assets/15310560/16064598/9e40a4b0-3270-11e6-950d-929f08c10210.png)
EXHIBIT B:
![1465951129](https://cloud.githubusercontent.com/assets/15310560/16064597/9e3ee120-3270-11e6-99d8-3a2251f3e594.png)

Just from viewing these two images of the files opened in Vim, it is clear something is not correct. Images do not seem to be saved with a METADATA_BLOCK_PICTURE tag like you would an artist name or something of that sort. If I search that phrase in the metaflac applied file, there is no match. 

I would be forever grateful if someone could get this figured out. I really like Mutagen, but if I can't tag OGG and FLAC files correctly, then I feel like I might just give up.

**Comment by lazka** [comment]
Looks like you are using the code to add embedded pictures to vorbis comment. FLAC, while using vorbis comment, uses something different for pictures. Here is an example: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/formats/xiph.py#L432

**Comment by tmose1106** [comment]
I suppose this is a little off topic, but before I attempt to modify your xiph script for my own purposes I wanted to try using ExFalso to see if it really worked as intended, and I receive the error here: 
[Dump_20160615_102727.txt](https://github.com/quodlibet/mutagen/files/316324/Dump_20160615_102727.txt)

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
exfalso also ships a command line tool, btw:

`operon image-set cover.jpg song.flac`

**Comment by tmose1106** [comment]
Thanks for the tip on the operon tool! It seems to work great with FLAC files. But I ran into this error while trying to repeat the process on a OGG Vorbis file: 
![1466004038](https://cloud.githubusercontent.com/assets/15310560/16085834/6c981724-32eb-11e6-822c-459f92dfdd11.png)

**Comment by lazka** [comment]
quodlibe/exfalso/operon are python2. In case you are on Arch, all three should be installed with the "quodlibet" package.

**Comment by tmose1106** [comment]
Are you aware of how I could recreate this functionality using python3, or basically solve the string error above?

**Comment by lazka** [comment]
Not until I get to fixing operon tests under Python 3. But Python 2 should work just fine.

**Comment by tmose1106** [comment]
Alright, well thank you for the time being. My cellular device is able to read the OGG Vorbis art added via operon, but the Deadbeef music player can not, so I will go pick a fight with them next. Thank you for your help!
