### ISSUE TITLE
Use copy_file_range() on linux

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#264]
Bugs:

https://bugzilla.kernel.org/show_bug.cgi?id=135461
https://bugzilla.kernel.org/show_bug.cgi?id=135451

Example code: https://gist.github.com/lazka/78bdfdbf8b01f1514f1c801acf321930

Man page: http://man7.org/linux/man-pages/man2/copy_file_range.2.html

Should help with #230

**Comment by lazka** [comment]
Would also help with the copy part of atomic saving.

**Comment by lazka** [comment]
Sadly copy_file_range is broken for that use case.

**Comment by lazka** [comment]
To clarify since I had a look into this again because it is now exposed in Python. When I first tested it, it produced garbage results for overlapping ranges.

The man page was now update to state that overlapping ranges are not allowed:

> fd_in and fd_out can refer to the same file.  If they refer to the
       same file, then the source and target ranges are not allowed to
       overlap.

**Comment by giampaolo** [comment]
>  fd_in and fd_out can refer to the same file.

I wonder what's the use case (why would you want to have the same src and dst file?).

**Comment by lazka** [comment]
We need to insert an empty block at the beginning of large files which means first adding an empty block at the end and then moving the whole content by that.
