### ISSUE TITLE
ID3 version header not updatable

### ISSUE THREAD

**Issue by s0ph0s-2** [quodlibet/mutagen#265]
As far as I can tell, there is no way to update the ID3 version header (bytes 4 and 5 of the file) using mutagen.  
Steps for replication:  
* Create an MP3 file with ID3v2.3 tags and headers
* Load it into mutagen with `f = mutagen.id3.ID3("with-v23.mp3")`. The documentation states this automatically runs the `update_to_v24()` function, which converts all tags to their v2.4 equivalents.
* Save the file with `f.save()`  

The first five bytes of the file *should* now be `49 44 33 04 00`, but are actually `49 44 33 03 00`.  
Additionally, I tried to manually set the version with:  
* `f.version = (2, 4, 0)`
* `f._version = (2, 4, 0)`  

Both of those operations resulted in no change to `f.version`'s value, and running `f.save()` after each also did not update the header on disk. Based on the presence of a setter for `ID3.version` [here](https://github.com/quodlibet/mutagen/blob/master/mutagen/id3/_file.py#L87), I don't understand why setting it doesn't do anything.  
Although it's a semi-unusual corner case, this bug prevents files created with ID3v2.3 tags from being updated to use ID3v2.4 features (like chapters), even when all tags present in the file are from ID3v2.4.

**Comment by s0ph0s-2** [comment]
Actually, it looks like it's putting the updated v2.4 frames in a new ID3 tag at the end of the file with the correct header. Why doesn't it edit the tag that's already there?

**Comment by s0ph0s-2** [comment]
I'm still working on providing an example, but I'm having difficulty reproducing it myself. It works properly in my test scripts, but not in the larger program where I encountered the unusual behavior. In the meantime, here's [that code](http://pastebin.com/f3gv13iX), [the mp3 file I'm using it on](https://s0ph0s.cf/fnt-edit/fnt-177-clean.mp3), and [the JSON file the code reads from](http://pastebin.com/LkuZv9JK).  
I hope I haven't needlessly opened an issue…

**Comment by lazka** [comment]
> I'm still working on providing an example, but I'm having difficulty reproducing it myself. It works properly in my test scripts, but not in the larger program where I encountered the unusual behavior. In the meantime, here's that code, the mp3 file I'm using it on, and the JSON file the code reads from.

I'll have a look some time

>  I hope I haven't needlessly opened an issue… 

No problem at all. I'm glad someone finds the new chapter stuff useful.

btw. mutagen has no support for writing ID3 tags to the end of files, so if it ends up there it must be another tool (or a really weird bug of course)

**Comment by s0ph0s-2** [comment]
Aha! I've located the issue! I passed mutagen a `BufferedRandom` in mode `ab+`, which is why the tag ended up at the end of the file. If I call `p.seek(0)` though, it returns the read point to the beginning of the file, fixing the issue. I'll work on a pull request that adds support for this particular corner case.

**Comment by lazka** [comment]
As noted here https://mutagen.readthedocs.io/en/latest/user/filelike.html

"Mutagen expects the file offset to be at 0 for all file objects passed to it."

I didn't want to make people depend on mutagen doing the seek as I want to have the possibility to allow parsing from some random point in the future.

**Comment by s0ph0s-2** [comment]
Ah. I missed that bit! Thanks for your help!

**Comment by lazka** [comment]
If anything is unclear, feel free to open another issue.
