### ISSUE TITLE
Mutagen damages MP4 files?

### ISSUE THREAD

**Issue by remino** [quodlibet/mutagen#266]
Once I update the metadata in any MP4 file using `mid3v2` or `mid3cp`, that file will no longer be playable in iTunes. Some players will still accept and play the file, like VOX, but anything using QuickTime (including iTunes) will no longer read the file.

Version info:

```
$ mid3v2 --version
mid3v2 1.3
Uses Mutagen 1.34.1
```

**Comment by lazka** [comment]
mid3v2 adds ID3 tags to the files, which is not compatible with MP4 files.

Does "mid3v2 -D foo.mp4" make it work again?

**Comment by remino** [comment]
I was starting to suspect that. When I read the docs where it said MP4
files were supported, I thought ID3 tags were okay with them, or that
Mutagen was using a different format for those files.

I didn't try -D, but fortunately, this was just for a shell script. Nothing
was lost.

Using "ffmpeg -metadata" seems to be working better for me in this case.



-- 
Rémi

RÉMINO
https://remino.net/

**Comment by lazka** [comment]
We do have a command line tagger supporting MP4 in quodlibet called operon, but no binary available for OSX atm (I guess you use OSX?)

https://quodlibet.readthedocs.io/en/latest/guide/commands/operon.html

**Comment by remino** [comment]
Yes, I use OS X. I'll have to take a look at operon. Thanks.

By the way, I can confirm `-D` fixes my MP4 files.
