### ISSUE TITLE
Bad tags in mp3 

### ISSUE THREAD

**Issue by rsd** [quodlibet/mutagen#269]
I believe this is a bug in Mutagen.
I am trying to get all ID3 tags from a mp3 file.

basically the code is:
```
id3 = ID3("file.mp3")
for key in id3:
    print(key + "|")
```
The output is:

> TLEN|
> TCOP|
> PRIV::XMP<?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?>
> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c132 79.159330, 2016/05/06-01:10:55        ">
>  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
>   <rdf:Description rdf:about=""
>     xmlns:xmpDM="http://ns.adobe.com/xmp/1.0/DynamicMedia/"
>     xmlns:xmp="http://ns.adobe.com/xap/1.0/"
>     xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
>     xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
>     xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#"
>     xmlns:dc="http://purl.org/dc/elements/1.1/"
>    xmp:MetadataDate="2016-09-03T14:33:06-03:00"
>    xmp:ModifyDate="2016-09-03T14:33:06-03:00"
>    xmpMM:InstanceID="xmp.iid:e4b352a1-4c2a-4ab3-ad8a-b2ecbe132ab9"
>    xmpMM:DocumentID="xmp.did:e4b352a1-4c2a-4ab3-ad8a-b2ecbe132ab9"
>    xmpMM:OriginalDocumentID="xmp.did:27cb3be9-5214-43be-b8ac-7733d97e33fb"
>    dc:format="audio/mpeg">
>    <xmpDM:Tracks>
>     <rdf:Bag>
>      <rdf:li
>       xmpDM:trackName="CuePoint Markers"
>       xmpDM:trackType="Cue"
>       xmpDM:frameRate="f44100"/>
>      <rdf:li
>       xmpDM:trackName="CD Track Markers"
>       xmpDM:trackType="Track"
>       xmpDM:frameRate="f44100"/>
>      <rdf:li
>       xmpDM:trackName="Subclip Markers"
>       xmpDM:trackType="InOut"
>       xmpDM:frameRate="f44100"/>
>     </rdf:Bag>
>    </xmpDM:Tracks>
>    <xmpMM:History>
>     <rdf:Seq>
>      <rdf:li
>       stEvt:action="saved"
>       stEvt:instanceID="xmp.iid:27cb3be9-5214-43be-b8ac-7733d97e33fb"
>       stEvt:when="2016-09-03T14:33:06-03:00"
>       stEvt:softwareAgent="Adobe Audition CC 2015.2 (Macintosh)"
>       stEvt:changed="/metadata"/>
>      <rdf:li
>       stEvt:action="saved"
>       stEvt:instanceID="xmp.iid:e4b352a1-4c2a-4ab3-ad8a-b2ecbe132ab9"
>       stEvt:when="2016-09-03T14:33:06-03:00"
>       stEvt:softwareAgent="Adobe Audition CC 2015.2 (Macintosh)"
>       stEvt:changed="/"/>
>     </rdf:Seq>
>    </xmpMM:History>
>    <xmpMM:DerivedFrom
>     stRef:instanceID="xmp.iid:27cb3be9-5214-43be-b8ac-7733d97e33fb"
>     stRef:documentID="xmp.did:27cb3be9-5214-43be-b8ac-7733d97e33fb"
>     stRef:originalDocumentID="xmp.did:27cb3be9-5214-43be-b8ac-7733d97e33fb"/>
>   </rdf:Description>
>  </rdf:RDF>
> </x:xmpmeta>
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                                                                                                     
>                            
> <?xpacket end="w"?>|
> TALB|
> APIC:|
> TCON|
> TPUB|
> TDRC|
> TCOM|
> TENC|
> TSOP|
> TPE1|
> TIT1|
> TIT2|
> COMM::XXX|

What is the XXX in the COMMent?
Why the APIC has a : at the end of the tag?

I believe the XMP in the PRIVate is the samething as the XXX in the COMMent.
However, I am pretty sure that somewhere Mutagen did a wrong parsing and mixed the TEXT in.  Right?

-rsd

**Comment by lazka** [comment]
The keys are mostly (besides the name) an implementation detail and contain everything that makes the corresponding frame unique.

Try

```
id3 = ID3("file.mp3")
for v in id3.values():
    print(v)
```

to get a better overview


> What is the XXX in the COMMent?

the content if the language field

>  Why the APIC has a : at the end of the tag?

The hash key of the APIC frame is "APIC:<description>". In this case the description is empty.

> I believe the XMP in the PRIVate is the samething as the XXX in the COMMent.

Only one frame with the same content is allowed, so the key contains the data content.

**Comment by rsd** [comment]
ok,
So, how do I get/loop every available id3 tag?

**Comment by lazka** [comment]
ID3 implements the dict interface, the frames are the values.

Either (assuming you use Python 3):
```
for frame in id3.values():
    print(frame)
```

or

```
for key in id3:
    print(id3[key])
```

**Comment by rsd** [comment]
The values() works fine.  But I don't know which tag is it related to.

**Comment by lazka** [comment]
Not sure what you mean. What are you trying to do?

**Comment by rsd** [comment]
I am trying to get a list of all Tags in a mp3 file.
I was looping with a "for keys in mp3:", which was fine until I got the PRIV key above.

However, I believe I am doing it in the wrong way there should be a more intuitive way to get the tags/frames.

**Comment by lazka** [comment]
My previous example gives you all frames in the file. Maybe you want this instead:

```
from mutagen.easyid3 import EasyID3

EasyID3("file.mp3")
...
```

**Comment by rsd** [comment]
Sorry, I fail to see it.
Using EasyID3() will not retrieve the PRIV frame for example.

Looping thru the keys the PRIV will be returned will the full content in the key, as I showed in the the first post.
Maybe I am asking it wrong, sorry.
1 - Is this the only way to loop the available frames/tags?  (i=ID3(file);for k in i:...)
2 - If yes, I heva to clean up the key then? or
3 - Can I loop the frames instead of the tags?

thanks for the patience

**Comment by lazka** [comment]
1) The frames are the values, so values() gives you the frames
2) not sure what you mean with "clean up"?
3) Yes, "for frame in id3.values()"

If you want the PRIV frames you can use `id3.getall("PRIV")`

**Comment by rsd** [comment]
1-when I user values(), how do I know which tag it belongs to?
3- I would have to know that PRIV exists in the first place for this file.
2- Like in this key example:
PRIV::XMP<?xpacket begin="ï»¿" id=" ....

**Comment by lazka** [comment]
> 1-when I user values(), how do I know which tag it belongs to?

frame instances have a "FrameID" property.

> 3- I would have to know that PRIV exists in the first place for this file.

If no PRIV exists you get back an empty list.
