### ISSUE TITLE
mid3v2 output not emitting utf-8

### ISSUE THREAD

**Issue by bll123** [quodlibet/mutagen#271]
Something has changed in the output of mid3v2 and it is no longer emitting utf-8 data.

In both of these cases, the PYTHONIOENCODING environment variable is set to 'utf-8', though I believe that is not necessary with 1.34.1.

I have removed much of the output below, as only TIT2 is relevant.

=== mutagen 1.34.1  (working)

```
17:26:08       mp3:C:/Users/bll/Desktop/BallroomDJ/test.dir/music dir/130.01.255 unicodeã¯ã¯ã¯.mp3
17:26:08 mp3:raw:-- C:/Users/bll/Desktop/BallroomDJ/test.dir/music dir/130.01.255 unicodeã¯ã¯ã¯.mp3 
- MPEG 1 layer 3, 64000 bps (CBR?), 48000 Hz, 1 chn, 304.54 seconds (audio/mp3)
TIT2=130.01.255 unicodeã¯ã¯ã¯
```

=== mutagen 2016-9-25 (not working)

```
17:20:12       mp3:C:/Users/bll/Desktop/BallroomDJ/test.dir/music dir/130.01.255 unicodeã¯ã¯ã¯.mp3
17:20:12 mp3:raw:-- C:/Users/bll/Desktop/BallroomDJ/test.dir/music dir/130.01.255 unicode???.mp3
- MPEG 1 layer 3, 64000 bps (CBR?), 48000 Hz, 1 chn, 304.54 seconds (audio/mp3)
TIT2=130.01.255 unicode???
```

**Comment by lazka** [comment]
Are you redirecting stdout?

**Comment by lazka** [comment]
I'll have a look, thanks

**Comment by bll123** [comment]
Yes, it's an exec from Tcl, so stdout would be redirected into a pipe.  
I forgot to mention that this is a problem on windows.

**Comment by lazka** [comment]
Yeah, thanks. I'll try to make it work as before again.

**Comment by lazka** [comment]
fyi, the new release installs exe launchers, so you have to adjust your script to call mid3v2.exe.
I hope that's OK.
