### ISSUE TITLE
windows: error running mid3v2

### ISSUE THREAD

**Issue by bll123** [quodlibet/mutagen#273]
When running mid3v2 (1.35), this prints over and over.
```
Traceback (most recent call last):
  File "C:/Python27/Scripts/mid3v2", line 23, in <module>
    from mutagen._toolsutil import split_escape, SignalHandler, OptionParser
ImportError: No module named _toolsutil
```

Sorry not familiar at all with the python ecosystem, what does this error mean?
Both Windows XP pro 32 bit, python 2.7 and Windows 7 64 bit python 3.4.

**Comment by lazka** [comment]
Hm, I should have left the script for backwards compat I guess.

Since 1.35 mutagen installs exe launchers so `C:/Python27/Scripts/mid3v2.exe` should work.

**Comment by bll123** [comment]
No, that's not a big problem (though I have exec ..../python.exe  .../mid3v2 (and mutagen-inspect) to fix up and make compatible with both methods).

The installation left the old scripts behind, so my application still found the scripts.  Otherwise I would have noticed.  I am just doing: python setup.py install -f (build first of course).
I think the documentation should be more explicit about that type of change.

Is there an easy way to clean up 1.35 and revert to older versions?  I ended up removing the entire python install and rebooting the last time.  For some reason installing a prior version over 1.35 didn't work out very well.

Looks like I can just run mutagen-inspect-script.py instead, right?
Running the script directly works.
It seems slower than before.  I will have to do a timing test.

Running the executable does not work. It gets this error.
[Errno 22] Invalid argument: 'C:/Users/bll/Desktop/BallroomDJ/test.dir/music dir
/130.01.37 unicode???.mp3'

**Comment by bll123** [comment]
Timing:
2016-10-25: 208 seconds
1.35: 362 seconds (and had any benefits of OS caching).

This was just one piece of my application testing.    It runs mutagen-inspect, mid3v2 --delete-frames and mid3v2 to set the tags on a bunch of test music files.

**Comment by lazka** [comment]
OK, I'll revert mutagen back to distutils for now.
