### ISSUE TITLE
Trailing whitespace when listing tags.

### ISSUE THREAD

**Issue by joaoe** [quodlibet/mutagen#274]
Hi ! 

When I run mutagen with
```
mid3v2 -l <file>
```
I'll get the list of tags. The last one will have a trailing whitespace that does not exist in the file. Since I'm running mutagen in a script that sanitizes mp3 tags, it will always think files have content that can be sanitized due to that trailing space (trimming tags is one of its features).

Anyway, this is a trivial issue, in `mutagen/_toolsutil.py`, function `print_`.

The following to lines are the culprit:
```
objects = list(objects) + [os.linesep]
data = (b" " if sep else b"").join(parts)
```
The `.join()`will add the whitespace before the newline.

Tip: replace with just 
```
data = (b" " if sep else b"").join(parts) + (os.linesep if linesep else b"")
```

**Comment by lazka** [comment]
Thanks for the report!

This should already be fixed in the newest version.

**Comment by joaoe** [comment]
Looks like indeed it is. Thanks !
