### ISSUE TITLE
MP4: Add method for deleting a specific tag

### ISSUE THREAD

**Issue by bernd-wechner** [quodlibet/mutagen#275]
mutagen.mp4.MP4Tags has a delete method which deletes all tags. 

What appears to be missing is a means of deleting a specific tag. 

The equivalent of:

`mutagen.id3.ID3Tags.delall(key)`
`mutagen.asf.ASFTags.__delitem__(key)`

(oddly inconsistent implementation already in IDTags and ASFTags).

**Comment by lazka** [comment]
You can just use .pop() or del

ID3Tags has delall because the real keys are not known to the user.
`mutagen.asf.ASFTags.__delitem__` is what is called when you do `del tags["foo"]`

**Comment by bernd-wechner** [comment]
Awesome! Thanks for the clarification lazka. And my apologies for not finding that autonomously. But perhaps indicates a small improvement that can be made to the docs at readthedocs? Or to my detective skills using them? I did do quite some reading and web searching before I bothered to file an issue believe me, it was at the tail end of some considerable invested effort to work that out (and failing).

**Comment by lazka** [comment]
No problem at all. The tutorial for MP4 in the docs is pretty much empty, so not much you can do besides asking :)

I'd suggest you have a look at what quodlibet does for each format. It usually contains the most common API usage patterns: https://github.com/quodlibet/quodlibet/tree/master/quodlibet/quodlibet/formats
