### ISSUE TITLE
mid3cp removes old tags

### ISSUE THREAD

**Issue by charlesmilette** [quodlibet/mutagen#277]
I'd like to use it as a way to merge tags from two files (One has BPM, encoder but the other one has title, artist) into a single file, but the tool erases all old tags before copying (something that the original id3cp does not)

A better behavior would be to keep them and ask the user what to do if there is any conflicts during the progress.

**Comment by lazka** [comment]
Sounds good. We should do what id3cp does by default at least. Thanks for
the report.

**Comment by charlesmilette** [comment]
id3cp does not ask for conflict, it creates a new tag element with the same type, creating a duplicate tag in the file. mid3cp could have an argument for each behavior (ask, overwrite, ignore or id3cp-like) and one to keep or remove old tags before copying. But it should also default to the old versions' behavior when no argument is provided, to not break scripts.

**Comment by lazka** [comment]
I've just tested with id3cp and it also deletes all tags from the destination file first.

**Comment by charlesmilette** [comment]
id3info still shows me the precedent tags when I use it, but not with
mid3cp.

Le mer. 30 nov. 2016 05:56, Christoph Reiter <notifications@github.com> a
écrit :

**Comment by lazka** [comment]
This is what I get 

```
lazka@debian> id3info a.mp3

    *** Tag information for a.mp3
    === TIT2 (Title/songname/content description): Das Boot
    === TPE1 (Lead performer(s)/Soloist(s)): Absolute Beginner
    === TLEN (Length): 249000
    *** mp3 info
    MPEG1/layer III
    Bitrate: 128KBps
    Frequency: 44KHz
lazka@debian> id3info b.mp3

    *** Tag information for b.mp3
    === TIT2 (Title/songname/content description): Elephant Gun
    === TPE1 (Lead performer(s)/Soloist(s)): Beirut
    === TALB (Album/Movie/Show title): Lon Gisland EP
    === TRCK (Track number/Position in set): 1
    *** mp3 info
    MPEG1/layer III
    Bitrate: 192KBps
    Frequency: 44KHz
lazka@debian> id3cp --version
    id3cp 3.8.3
lazka@debian> id3info --version
    id3info 3.8.3
lazka@debian> id3cp
    Usage: id3cp [OPTIONS] SOURCE DEST
lazka@debian> id3cp a.mp3 b.mp3
    Parsing a.mp3: done.  Copying to b.mp3: done
lazka@debian> id3info b.mp3

    *** Tag information for b.mp3
    === TIT2 (Title/songname/content description): Das Boot
    === TPE1 (Lead performer(s)/Soloist(s)): Absolute Beginner
    === TLEN (Length): 249000
    *** mp3 info
    MPEG1/layer III
    Bitrate: 192KBps
    Frequency: 44KHz
    lazka@debian>
```

**Comment by lazka** [comment]
I'm still OK with adding an option to keep the tags, but as far as I can see the default behavior matches that of id3cp

**Comment by charlesmilette** [comment]
My bad, I added the `-1` argument. The old v2 tags weren't removed because
of that, resulting in me seeing the old v2 tags combined with the new v1
tags when I use `id3info`.

Le mer. 30 nov. 2016 13:10, Christoph Reiter <notifications@github.com> a
écrit :

**Comment by lazka** [comment]
ok, thanks for checking.

Any opinions on how to call the switch? `--merge`? 
And should we use the target or source id3 version?

**Comment by charlesmilette** [comment]
`--merge`: Do not erase the old tags before copying
`--ask`: Ask what to do in case of conflicts. (default) (requires `--merge`)
`--overwrite`: Automatically overwrite the tags of the destination with the tags from the source in case of conflicts. (requires `--merge`)
`--ignore`: Keep the tags from the destination in case of conflicts. (requires `--merge`)

The ID3 version is up to your preference.

**Comment by lazka** [comment]
Proposed implementation here: https://github.com/quodlibet/mutagen/pull/280

I don't like adding that many options if there is no common use case for it. It makes the implementation more complex and makes reading the help output and man page harder for not much gain.

Does the functionality outlined in #280 cover your use case, or did I miss anything?

**Comment by charlesmilette** [comment]
It seems fine to me.

**Comment by lazka** [comment]
OK, thanks.
