### ISSUE TITLE
Mutagen saves ID3 V2.3 tags in an unusual order

### ISSUE THREAD

**Issue by Knutz99** [quodlibet/mutagen#278]
Loading and re-saving V2.3 tags results in the tag order being somewhat unusual with any embedded artwork in the middle of text tags.
Can the default order be changed to put APIC last or can they be saved in a reverse size order.

More details in the mailing list:
https://groups.google.com/forum/#!topic/quod-libet-development/DuN0Bu-MEN0

Thanks
Bob

**Comment by lazka** [comment]
Thanks!
