### ISSUE TITLE
Support Google App Engine Standard Runtime

### ISSUE THREAD

**Issue by mike-matera** [quodlibet/mutagen#286]
Hi, 

GAE does not support the 'mmap' library in Python. Applications have no direct access to files at the operating system level. The runtime does support file-like objects that can, read, write, seek, etc. In the current version of mutagen it's possible to read ID3 tags from a file if the "import mmap" line is changed in _util.py to be:

```
try : 
   import mmap
except : 
   pass
```

I'm happy to help by providing testing and any environment setup documentation. Just ask. 

Thanks!
./m

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
fyi, more info for working with file-like objects: https://mutagen.readthedocs.io/en/latest/user/filelike.html

**Comment by mike-matera** [comment]
Thanks! This works for me. In case you're interested here's some more detail about using App Engine and Cloud Storage:

There are two APIs for accessing cloud storage in AppEngine. One gives a file-like object, which works for reading tags. The file-like API only transfers blocks of the file that the application requests. Which is great because it takes much less than one second to read the ID3 tags in a 100MB MP3 file. 

Writing tags is a different story. Google Cloud Storage blobs are immutable (they can't be written). A blob update therefore is a read-modify-write. In the case of writing tags the whole MP3 would have to be pulled down modified locally and rewritten. Which can get expensive if you have long files (like two-hour DJ mixes). It's not clear to me whether it's even possible to do this in App Engine. If I ever try it I'll let you know. 

Thanks again!

**Comment by lazka** [comment]
Thanks for the info.

mutagen does quote a lot of read/seek calls when parsing; not sure how the file-like is implemented, but in case those operations have a large overhead looking into caching might speed things up a bit. Maybe they can be wrapped with io.BufferReader?
