### ISSUE TITLE
Picard slowness over Windows network share

### ISSUE THREAD

**Issue by Sophist-UK** [quodlibet/mutagen#288]
Using Picard over a Windows 10 network share I have been getting very poor performance. Windows task manager shows open handles growing.

This issue is to log the possibility of a file handle leak in Mutagen creating these performance problems.

Ongoing discussion re: Picard is in ticket [PICARD-744](https://tickets.metabrainz.org/browse/PICARD-744) but for MP3 files it looks to me like the code reads the header to determine the ID3 data size, and at ID3/_file.py:164 calls ._util.py:read_full which reads the rest of the ID3 data (using the size in the header) but does NOT read to the end of the file (which would implicitly close the file) or does it close the file explicitly.

I haven't looked at other formats, but this may apply to them as well as ID3.

Do we need to explicitly close the file at the end of the `load` method?

**Comment by lazka** [comment]
Which mutagen version do you ship with picard? That code has changed considerable when file object support was added in 1.33.

Currently closing is handled (a bit magic..) https://github.com/quodlibet/mutagen/blob/master/mutagen/_util.py#L102

**Comment by Sophist-UK** [comment]
I guess you are suggesting that code like:
```
            with _openfile(self, filething, filename, fileobj,
                           writable, create) as h:
                return func(self, h, *args, **kwargs)
```
does an implicit close when you exit the with block and h (which contains the file handle) is de-assigned and all references to the handle are gone. 

But I wonder whether the file is actually closed only **during python garbage collection**?

And whether we need to do an explicit close anyway?

**Comment by lazka** [comment]
The exit code of context managers does not depend on the GC.

**Comment by lazka** [comment]
Running the tests suite with all warnings does not indicate that we leak any file object there. I also can't find any place where we open a file without a context manager.

**Comment by Sophist-UK** [comment]
`_openfile` returns a FileThing which is a namedtuple:

https://github.com/quodlibet/mutagen/blob/master/mutagen/_util.py#L169

So for this implicit close to happen by the __exit__() method of the file class when the `with` context is exited, the tuple subclass returned by the namedtuple function will need to have `__enter__()` and `__exit__()` methods defined and then to propagate those to each of the tuple members. I am unclear whether this is the case or not in Python.

Perhaps someone could write a test class with an `__exit__()` method which outputs a debug message, and then try it as a namedtuple used in a `with` context  manager.

**Comment by Sophist-UK** [comment]
Hmm - just found this page which gives an almost exact example:

https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/

And his code has an **explicit** close after the `yield` statement:
```
@contextmanager
def open_file(path, mode):
    the_file = open(path, mode)
    yield the_file
    the_file.close()
```

**Comment by Sophist-UK** [comment]
As an aside, all this stuff with decorators is definitely very clever, indeed very very very clever, but it sure makes it hard to read the code and understand what is happening when it runs.

**Comment by lazka** [comment]
Is there any difference if you disable the mmap monkey patching code in picard? I seems to do some locking, maybe that doesn't play well with network shares.

**Comment by Sophist-UK** [comment]
Ok - I just tested it with the following code added:
```
        with fileobj as fileobj:
            yield FileThing(fileobj, filename, filename)
            print "After yield file " + filename + " is " + ("closed" if fileobj.closed else "open")
        print "After with file " + filename + " is " + ("closed" if fileobj.closed else "open")
```
and got the following output:
```
After yield file x.mp3 is open
After with file x.mp3 is closed
```
So it does appear that exiting the `with` context closes the file.

**Comment by Sophist-UK** [comment]
That was with (a year old) version of Picard source code.

So I doubt that the monkey map is causing any issue.

**Comment by Sophist-UK** [comment]
However a few lines earlier there is a context manager missing which will leave the file open:

https://github.com/quodlibet/mutagen/blob/master/mutagen/_util.py#L206
```
    if fileobj is not None:
        verify_fileobj(fileobj, writable=writable)
        yield FileThing(fileobj, filename, filename or fileobj_name(fileobj))
```
which I think should be:
```
    if fileobj is not None:
        verify_fileobj(fileobj, writable=writable)
        with fileobj as fileobj:
            yield FileThing(fileobj, filename, filename or fileobj_name(fileobj))
```

**Comment by lazka** [comment]
On Sat, Jan 21, 2017, 20:29 Sophist <notifications@github.com> wrote:

> That was with (a year old) version of Picard source code.
>
> So I doubt that the monkey map is causing any issue.
>

Why do you think that?

BTW a year old Picard implemented id3 saving itself, it was ported to
mutagen a few months ago.

**Comment by Sophist-UK** [comment]
Or perhaps not - if fileobj is not None then we probably don't want to close it.

I added a print line after the previous Yield statement and added a timestamp and got the following:
```
19:58:03 After existing file is open
19:58:03 After yield file x.mp3 is open
19:58:12 After with file x.mp3 is closed
```
So for a single file we seem to be running through both code paths.

**BUT** note the 9 seconds time difference between the last two lines. which you would think would be executed immediately. No idea what the cause of this is though.

**Comment by Sophist-UK** [comment]
Just updated to latest source code and results are the same.

So no idea why both code paths are run and no idea why there is a 7sec-9sec delay between.

My guess is that it is a garbage collection delay, but that is just a guess.

**Comment by lazka** [comment]
On Sat, Jan 21, 2017, 21:19 Sophist <notifications@github.com> wrote:

> Just updated to latest source code and results are the same.
>
> So no idea why both code paths are run and no idea why there is a
> 7sec-9sec delay between.
>
close() is called in between

**Comment by lazka** [comment]
Not sure what to do here. If you find out anything new, feel free to post here or open a new one.

**Comment by Sophist-UK** [comment]
I have written a fix for a lot of the issues that made Picard appear slow. They should appear in Picard 1.4.1 (took late to make the cut for 1.4 which is scheduled to be repeat tomorrow). 

However there is still a handle leak - though I have a feeling it might be a network handle rather than a file handle. 

So happy for this to be closed.

**Comment by Sophist-UK** [comment]
And thanks for your help.

**Comment by Christilut** [comment]
Was this ever solved in mutagen? Whenever I use mutagen in bulk on a Windows network share (samba) it starts fast but slows down to a near grinding halt shortly after.

I can make a repro, but just wondering if something was done on this front or maybe this is a known issue currently?
