### ISSUE TITLE
TDRC vs. TDRL

### ISSUE THREAD

**Issue by pR0Ps** [quodlibet/mutagen#290]
Currently it seems like the 'date' of a track is mapped to the `TDRC` frame (recording date) instead of `TDRL` (release date).

This can be seen in a few places:
 - The [mid3v2 docs](https://github.com/quodlibet/mutagen/blob/ddf22e36b0ae9afff8a6ed4ba08439451a5af748/docs/man/mid3v2.rst#options)
 - [`easyid3.py`](https://github.com/quodlibet/mutagen/blob/ccba9efea0741ab42a21f4c9109a73020dad0adf/mutagen/easyid3.py#L278-L287) and [it's tests](https://github.com/quodlibet/mutagen/blob/ccba9efea0741ab42a21f4c9109a73020dad0adf/tests/test_easyid3.py#L55-L63)

Is this a bug? Or was this done on purpose for compatibility reasons?

For reference, excerpts from the [id3v2.4 spec](http://id3.org/id3v2.4.0-frames):
 - `TDRC`: "Recording time [...] when the audio was recorded".
 - `TDRL`: "Release time [...] when the audio was first released"
 - `TDOR`: "Original release time [...] when the original recording of the audio was released"

**Comment by lazka** [comment]
Everyone does it. I think it started because iTunes wrote dates as TDRC.

https://picard.musicbrainz.org/docs/mappings/
http://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping

**Comment by lazka** [comment]
Having an official tag for this would of course be nice. I only know recording times from jazz albums, and there they are usually ranges or dates from concerts. Best to talk to the musicbrainz devs about it.
