### ISSUE TITLE
APIC Tag Uses Image Description

### ISSUE THREAD

**Issue by tmose1106** [quodlibet/mutagen#293]
Hello, I just wanted to say, it seems to me the way APIC keys are handled in mutagen 1.36.2 is not a very good approach. Creating keys of the form `APIC:<image-description>` does not seem like a good idea since there is no guarantee that a user's music library has standardized image descriptions. Couldn't we use the fact we know if an image is a front cover to create a key like `APIC:Cover_Front` or whatever type the image is?

This comes up because I am writing some scripts to deal with my music library, and some of my files have front covers with descriptions saying "Front Cover" and others are the name of the file that was added as the front cover. I would like to be able to just say I want all the front covers. And this should be possible since that information is included in APIC tags, correct?

**Comment by sampsyo** [comment]
For what it's worth, is still possible to get all the APIC frames for a file—just use `file.tags.getall('APIC')`. (You can then filter them by type if you like.) That's how we do it for [MediaFile](https://github.com/beetbox/mediafile), anyway.

```py
>>> import mutagen
>>> m = mutagen.File('test/rsrc/image.mp3')
>>> [p.type for p in m.tags.getall('APIC')]
[<PictureType.COVER_FRONT: 3>, <PictureType.ARTIST: 8>]
```

**Comment by lazka** [comment]
I've added something to the user guide: https://mutagen.readthedocs.io/en/latest/user/id3.html#id3-dict-interface

**Comment by tmose1106** [comment]
Alright, I think that clears up my issue. Glad we could get that sorted out 👍
