### ISSUE TITLE
mp4 ©wrk

### ISSUE THREAD

**Issue by Sophist-UK** [quodlibet/mutagen#299]
I can't find official description of the mp4 ©wrk field on iTunes, but it seems to be part of the Classical Movement enhancements.

Is there a reason that this was not added in 1.37 with the Movement support?

**Comment by lazka** [comment]
I forgot to mention it in the docs. Since MP4() defaults to text for unknown items and "©wrk" is a text field it should work by default.

**Comment by lazka** [comment]
Same for "©mvn"
