### ISSUE TITLE
Handle tagging with gvfs fuse file systems

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#301]
https://tickets.metabrainz.org/browse/PICARD-985

https://bugzilla.gnome.org/show_bug.cgi?id=748106

**Comment by lazka** [comment]
was already opened: #300

**Comment by mattia-b89** [comment]
https://tickets.metabrainz.org/browse/PICARD-1135

**Comment by lazka** [comment]
yeah, seems likely
