### ISSUE TITLE
Mutagen writes, but won't read, multiple identical front cover images in MP3 files

### ISSUE THREAD

**Issue by marktaff** [quodlibet/mutagen#302]
Mutagen allowed me to write two identical front cover images, so now the files have two identical APIC tags. However, mutagen will only read one of them, nor will it tell me there are multiple front cover images so I could handle the issue.  mid3v2 only lists one APIC tag as well, while id3v2 lists both tags, and easyTAG also shows both front cover images.

`$ mid3v2 -l ../music/mp3/Queen/Greatest\ Hits\ I\ \&\ II/Queen\ -\ Under\ Pressure.mp3 
IDv2 tag info for ../music/mp3/Queen/Greatest Hits I & II/Queen - Under Pressure.mp3
APIC=cover front, Front cover (image/jpeg, 65082 bytes)
COMM=description=XXX=<rating>6</rating>
TALB=Greatest Hits I & II
`

`$ id3v2 -l ../music/mp3/Queen/Greatest\ Hits\ I\ \&\ II/Queen\ -\ Under\ Pressure.mp3 
id3v2 tag info for ../music/mp3/Queen/Greatest Hits I & II/Queen - Under Pressure.mp3:
TCON (Content type): Classic Rock (1)
APIC (Attached picture): (Front cover)[, 3]: image/jpeg, 65082 bytes
APIC (Attached picture): (Front cover)[, 3]: image/jpeg, 65082 bytes
COMM (Comments): (description)[XXX]: <rating>6</rating>
`

Both
`            d = mutagen.mp3.MP3(self.mp3Path)
            x = d.tags.getall('APIC')`
and
`self.apic = self.m.getall('APIC')`
where m is: `self.m = mutagen.id3.ID3(self.mp3Path, None, False, 3)`
only return one image, when a list of apic objects is expected.

It'd be nice if mutagen didn't write off-spec files, and it'd also be nice if mutagen would read off-spec apic tags so you could detect the off-spec condition and fix it.

**Comment by lazka** [comment]
> Mutagen allowed me to write two identical front cover images

How did you do this?

btw. mutagen should read off-spec duplicate APIC frames since 1.35

**Comment by marktaff** [comment]
I'm using 1.34, so that may be part of it.  I have a master flac tree in [artist]/[album]/*.flac.  I had an old script that created a similar mp3 tree based on that flac tree.  That script used id3v2 to embed front cover art with no desc.

I'm updating that script to add musicbrainz, ReplayGain, and additional tags, and with more robust coverart change detection for when I update the master cover art image, with the goal of deprecating id3v2.  I was testing APIC:None, and if it wasn't there I was writing the cover image to APIC:None, but with a spec with a desc.  That left me with two identical, but individually valid, front cover tags.

I hacked around this by using id3v2 to detect multiple front cover images so my script could delete all APIC and then just properly embed the correct one via `current.m['APIC:Front cover'] = mutagen.id3.APIC(enc, 'image/jpeg', 3, 'Front cover', current.imagedata)`

**Comment by lazka** [comment]
Ok. In the future never make up ID3 dict keys and always use ID3.add() to add frames, that will prevent the hashes getting out of sync. Some more info: https://mutagen.readthedocs.io/en/latest/user/id3.html#id3-dict-interface

If you update to a more recent version you should be able to recover those images (mutagen will append spaces to the desc when parsing duplicate APICs)

**Comment by marktaff** [comment]
Thanks.
