### ISSUE TITLE
iTunes 'GRP1' frame support

### ISSUE THREAD

**Issue by davconvent** [quodlibet/mutagen#304]
With iTunes' release of version 12, iTunes is now writing "Grouping" values from its library out to a new ID3 frame "GRP1". Support of this new "iTunes Grouping" frame in mutagen would be great addition.

**Comment by lazka** [comment]
sure, thanks

**Comment by lazka** [comment]
And "GP1" for id3v2.2

**Comment by lazka** [comment]
New release is out.
