### ISSUE TITLE
Inconsistent command line option syntax

### ISSUE THREAD

**Issue by mmcco** [quodlibet/mutagen#305]
All of the long-form options such as `--delete-frames` and `--picture` take an equals sign between its option and argument (e.g. `--delete-frames=TORY`). However, the options used to set frames don't, and they will silently include the equals sign in the tag itself. For example, `mid3v2 --TORY=1993 foo.mp3` will set the `TORY` frame to `=1993`. One can easily overlook this when using `mid3v2 -l foo.mp3`, too.

I can think of two possible solutions:

1. Strip the equals sign if the argument isn't quoted. This is a slight change in behavior, but there are extremely few cases in which someone would start a field value with an equals sign.
2. Print a warning to stderr when an argument matches this pattern.

Thanks for your time,
Mike

**Comment by lazka** [comment]
I can't reproduce with `mid3v2 --TORY=1993 foo.mp3`. The value is "1993" here.
