### ISSUE TITLE
USLT option listed but not supported.

### ISSUE THREAD

**Issue by hboetes** [quodlibet/mutagen#306]
Hi there, I tried adding lyrics to an mp3 file, but it wasn’t supported.
```% mid3v2 --USLT=’foo bar’ test.mp3
Usage: mid3v2 [OPTION] [FILE]…

mid3v2: error: no such option: --USLT
% mid3v2 -f|grep USLT             
    --USLT    Unsynchronised lyrics/text transcription.
```
Could you please add support for it? Also please consider adding said tag from a file, since lyrics are rather clumsy to add from the command line.

**Comment by lazka** [comment]
I made it work the same as COMM for now as I'd like to avoid adding more variations argument formats. If you have more complex use cases like reading from files I'd recommend writing a Python script.

```python
import sys
from mutagen import MutagenError
from mutagen.id3 import ID3, USLT, ID3NoHeaderError

try:
    tags = ID3(sys.argv[1])
except ID3NoHeaderError:
    tags = ID3()

with open(sys.argv[2], "rb") as h:
    text = h.read().decode("utf-8")
    tags.delall("USLT")
    tags.add(USLT(text=text, lang="eng", desc=""))

tags.save(sys.argv[1])
```
