### ISSUE TITLE
OggOpus returned a negative audio length

### ISSUE THREAD

**Issue by nasief** [quodlibet/mutagen#308]
When I tried to get the `length` of an `.ogg` audio file, the attribute returned a negative value!
The audio is 58 seconds long and it is playing normally without any issue.
What could be a reason for such a behavior?

**Comment by nasief** [comment]
I did some investigation within the library, I found that when trying to execute `self.info._post_tags(fileobj)` on the file, it tries to get the last page `OggPage.find_last(fileobj, self.serial)`, within this call, there is an initialization `page = OggPage(bytesobj)`, this tries to read the header and unpack it, the result is that `self.position` attribute is returned as `-1` and then `(page.position - self.__pre_skip) / float(48000)` yields a negative value for the length.

I am wondering, in such a case, could this be caused due to a problem in the header of the file or something else?

**Comment by lazka** [comment]
Can you send me the file to reiter.christoph@gmail.com?

**Comment by nasief** [comment]
@lazka should be in your inbox now

**Comment by lazka** [comment]
thanks

**Comment by lazka** [comment]
It's a mutagen bug. We don't handle the case of the last ogg page being empty. I don't know why the file contains one but it's not against the spec..

**Comment by nasief** [comment]
@lazka Thanks for taking the time to investigate the issue.
I don't know actually what caused such a case, we recorded it normally like other audio files we record (~100 files). 
How long do you think it will take for a fix to be released?

**Comment by lazka** [comment]
>  I don't know actually what caused such a case, we recorded it normally like other audio files we record (~100 files).

If you are using the official opus encoder, I suspect that this edge case is unlikely, because this is the first time it has come up and the code hasn't changed in years.

>  How long do you think it will take for a fix to be released?

No promises, maybe this week. Feel free to ping me if not.

**Comment by lazka** [comment]
```
$ mutagen-inspect 308.ogg
-- 308.ogg
- Ogg Opus, 55.62 seconds (audio/ogg)
```

Thanks for the report!

**Comment by nasief** [comment]
@lazka Thanks for the update. 
I did test it and it is working fine :)

**Comment by lazka** [comment]
New release is out.
