### ISSUE TITLE
Bypass conversion to ID3v1 genre list

### ISSUE THREAD

**Issue by williamjacksn** [quodlibet/mutagen#311]
I have a particular use case where I want to set the ID3v2 TCON (genre) tag to "2". But when I do that, upon reading back the tag, mutagen looks it up in the ID3v1 genre list (in `_constants.py`) and tells me the genre is "Country".

```python
>>> import mutagen.id3
>>> g = mutagen.id3.TCON()
>>> g.genres = ['2']
>>> g.genres
['Country']
```

Would it be possible to add some option to allow integer literals as the genre unchanged? This is the interface I first thought of:

```python
>>> import mutagen.id3
>>> g = mutagen.id3.TCON(literal=True)
>>> g.genres = ['2']
>>> g.genres
['2']
```

**Comment by lazka** [comment]
The problem at loading time is this: https://github.com/quodlibet/mutagen/blob/9e079a96e0d6bc42f47be3be5df9ab9bc313d13b/mutagen/id3/_tags.py#L349

Can you share your "particular use case"?

**Comment by williamjacksn** [comment]
> Can you share your "particular use case"?

Over at http://rainwave.cc we maintain a collection of video game soundtracks, covers, and remixes. We use the genre tag to indicate the video game series that a particular song belongs to (e.g. 'Mario' or 'Zelda'). Sometimes we have music from games that are the not part of a series, and in those cases, we simply set the genre to the game name.

We recently added music from [a video game called *2*](http://www.hubolhubolhubol.com/index.php?id=2), so we naturally tried to set the genre to '2'. And we saw 'Country' on the front-end.

**Comment by lazka** [comment]
Hm, ok thanks for the details. That's a bit against the spec, but I see how one would expect it to work either way.

If you are OK with a workaround, the following should work:

```
tags = ID3("foo.mp3", translate=False)
tcon = tags.getall("TCON")
tags.delall("TCON")
tags.update_to_v24()
tags.setall("TCON", tcon)
```

**Comment by williamjacksn** [comment]
Thanks for pointing out a workaround. I don't think I would have found `translate=False` on my own! This looks like exactly what I need.
