### ISSUE TITLE
Unable to recognize file-like objects

### ISSUE THREAD

**Issue by tjiang11** [quodlibet/mutagen#313]
I am trying to use mutagen to validate that audio files are of a given audio format. 

My problem is that I'm unable to get it to recognize anything when passing the file-like object itself to mutagen. However, I am able to get it to recognize the audio file when the file is stored locally and I pass in the filename. But no matter what I do, passing in a StringIO object always returns NoneType.

```
import mutagen
from StringIO import StringIO

filename = "test-audio-a.mp3"

f = open(filename)
mbuffer = StringIO()
mbuffer.write(f.read())

audio = mutagen.File(mbuffer)
print audio.pprint()

```
Results in `AttributeError: 'NoneType' object has no attribute 'pprint'`

**Comment by tjiang11** [comment]
The problem was resolved by adding `mbuffer.seek(0)` before passing to mutagen.

**Comment by lazka** [comment]
See https://mutagen.readthedocs.io/en/latest/user/filelike.html
