### ISSUE TITLE
MP4 - tags not recognized

### ISSUE THREAD

**Issue by gr4nt3d** [quodlibet/mutagen#323]
Hello,

there seems to be something missing with MP4 tags. As described [here](https://stackoverflow.com/questions/45763069/mutagen-does-not-recognize-mp4-itunes-voice-memo-tags) no tags are found in synchronized Apple voice-memo files. Note that these files _do have title_-information, that is being displayed in iTunes. The steps taken:

    import mutagen.mp4 as m
    f = m.MP4("file.m4a")
    print(f.tags) # see below
    print(f.MP4Tags()) # {}
    # f['\xa9nam'] = "test" # works
    print(f['\xa9nam']) # only works if edited by previous line or in iTunes

yields

    {'----:com.apple.iTunes:iTunSMPB': [MP4FreeForm(b' 00000000 00000840 000003E0 0000000007823BE0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000', <AtomDataType.UTF8: 1>)], '©too': ['com.apple.VoiceMemos (iOS 10.2)']}

**Comment by lazka** [comment]
Can you provide an example file?

**Comment by gr4nt3d** [comment]
It seems like the information is lost when separated from iTunes; in which case the title is stored somewhere else and mutagen can not find it. Could you check these files ?
If so: where do I find that certain title?

still visible title in iTunes
[20170902 130345.m4a.zip](https://github.com/quodlibet/mutagen/files/1272110/20170902.130345.m4a.zip)

delete from iTunes
[20170902 124113.m4a.zip](https://github.com/quodlibet/mutagen/files/1272101/20170902.124113.m4a.zip)

**Comment by lazka** [comment]
I can't find anything besides the info mutagen shows in the files. As you said, could be that they are stored in the iTunes DB.

This might help: https://support.apple.com/en-us/HT201610

**Comment by gr4nt3d** [comment]
Thanks, I could find that information in the mentioned xml.

Though, I've found some information, that working with that `*.xml` is not completely hassle-free. Do you happen to know how that `*.itl` is encoded or how to work with it ?

**Comment by lazka** [comment]
> Do you happen to know how that *.itl is encoded or how to work with it ?

No idea

**Comment by gr4nt3d** [comment]
Alright, thanks for the help and sorry for trouble; I thought it was stored in the files. Feel free to close this.

**Comment by lazka** [comment]
No problem, thanks for the report.
