### ISSUE TITLE
Strange bitrates reported, e.g. 320141 instead of 320000

### ISSUE THREAD

**Issue by mdeff** [quodlibet/mutagen#328]
When extracting the bitrate from many mp3 files, I get strange values such as 128111, 192167, 256222, or 320141 instead of the standards 128000, 192000, 256000, and 320000.

As I can only see the standard values in [mutagen/mp3/__init__.py](https://github.com/quodlibet/mutagen/blob/master/mutagen/mp3/__init__.py), I infer these numbers have to come from the file itself. Though the bitrate is correctly reported by other tools. Take for example [this audio file](http://freemusicarchive.org/music/Tours/Enthusiast/Tours_-_Enthusiast). With mutagen I get:
```
>>> f = mutagen.File('Tours_-_01_-_Enthusiast.mp3')
>>> f.info.bitrate, f.info.bitrate_mode
(320141, <BitrateMode.CBR: 1>)
```
With [eyeD3](https://eyed3.readthedocs.io):
```
>>> f = eyed3.load('Tours_-_01_-_Enthusiast.mp3')
>>> f.info.bit_rate
(False, 320)
```
Exiftool gives:
```
>>> exiftool Tours_-_01_-_Enthusiast.mp3
Audio Bitrate                   : 320 kbps
Encoder                         : LAME3.98r
Lame Method                     : CBR
Lame Bitrate                    : 255 kbps
```
Any idea? (What does "Lame Bitrate" mean BTW?)

**Comment by lazka** [comment]
uh, I guess because we don't ignore the encoder delay/padding for the calculation.

I think "lame bitrate" is the bitrate field in the lame header, which means in case of CBR, the minimum bitrate for each frame.

**Comment by mdeff** [comment]
Thanks for your answer. So it's a bug that will be fixed right? I.e. not an issue with the mp3 files.

In the mean time, do you know of a robust (i.e. valid for e.g. VBR mode too) way for me to correct the reported number?

**Comment by lazka** [comment]
yeah, I just noticed that lame includes the first frame in the byte count but not the frame count, will fix.

The files reported as unknown don't have a lame header, so we can't know the bitrate without going through the whole file.

**Comment by lazka** [comment]
pushed another fix

**Comment by mdeff** [comment]
Thanks! It looks much better now. The above table becomes:
![2017-11-02-14 14 02](https://user-images.githubusercontent.com/6806065/32328280-ba34cb4a-bfd9-11e7-85df-849000525386.png)

Looking at 10k mp3s, 830 are detected as CBR and 705 get a standard bitrate. The 105 others look like this:
![2017-11-02-14 30 39](https://user-images.githubusercontent.com/6806065/32328484-6c2f8baa-bfda-11e7-8293-3612e5509935.png)

Any more idea? I can send links to the mp3 files if it helps.

**Comment by mdeff** [comment]
> The files reported as unknown don't have a lame header, so we can't know the bitrate without going through the whole file, and the bitrate reported there is from the first frame.

That's good to know thanks. It should maybe be added to the doc.

**Comment by lazka** [comment]
From what I see this is due to lame having to add padding to some frames to hit the target bitrate, but that doesn't work out in all cases.

But feel free to send me a file (reiter.christoph@gmail.com)

**Comment by mdeff** [comment]
These are three faulty mp3 files (music is CC-licensed):
```python
for tid in [640, 6669, 14298]:
    f = mutagen.File(utils.get_audio_path(AUDIO_DIR, tid))
    print(f.info.bitrate, f.info.bitrate_mode)
    print('https://files.freemusicarchive.org/' + raw_tracks.at[tid, 'track_file'])
```

256007 BitrateMode.CBR
https://files.freemusicarchive.org/music/WFMU/Eric_Leonardson_and_Anna_Friz/Dancing_Walls_Stir_the_Prairies/Eric_Leonardson_and_Anna_Friz_-_Waltz_of_the_Parking_Meters.mp3
192132 BitrateMode.CBR
https://files.freemusicarchive.org/music/WFMU/Flaming_Fire/Live_at_WFMUs_Free_Music_Series__Southpaw_April_2007/Flaming_Fire_-_01_-_Fire_of_Love.mp3
255719 BitrateMode.CBR
https://files.freemusicarchive.org/music/no_curator/Zornjak/S_ljubavlju/Zornjak_-_Deset.mp3

**Comment by lazka** [comment]
Thanks

**Comment by mdeff** [comment]
You're welcome! Let me know if you find something.

**Comment by lazka** [comment]
The first two files had many frames with padding while the last file had none, so the bitrate looks correct.

**Comment by lazka** [comment]
I don't think there is anything left to do here, so closing. Thanks for the report!

I've extended the docs a bit in 102bef7a1e4990

If there are any remaining questions, please go ahead.

**Comment by mdeff** [comment]
Thank you for investigating and fixing the issues so quickly! :)

**Comment by lazka** [comment]
(a new release is out)
