### ISSUE TITLE
Single quote in file name, directory/file not found?

### ISSUE THREAD

**Issue by typistX** [quodlibet/mutagen#330]
```
artist_name = "This Artist"
song_title = "'This song with single quotes'"
album = "Live"

testFilePath = '~/Music/{} - {}.m4a'.format(artist_name, song_title) # Fails

metatag = MP4(testFilePath).tags
# title
metatag['\xa9nam'] = song_title
# album
metatag['\xa9alb'] = album
# artist
metatag['\xa9ART'] = artist_name

metatag.save(testFilePath)
```

The error I'm getting is `mutagen.MutagenError: [Errno 2] No such file or directory:...`

Obviously I can't just choose to remove the single quotes since this input is coming from an external source  that might contain single quotes in one of the strings.

**Comment by lazka** [comment]
The error indicates that you pass a path for a file which doesn't exist.

**Comment by typistX** [comment]
That I know. Please notice the title. The file exists 100%. If I remove the single quotes from the file and the string, everything works fine.

**Comment by lazka** [comment]
Hm, ok, so this succeeds?

```
import os

assert os.path.exists(testFilePath)
```

**Comment by typistX** [comment]
Hmmm...Actually that also fails, which I understand means this is not a mutagen issue. Again, if I remove the single quotes everything will work - I just don't understand how to get around it. But as it is not a mutagen issue I will close this and go look for a solution somewhere else.

**Comment by lazka** [comment]
Thanks for testing. Maybe the quotes in the filename are non-ASCII: https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
