### ISSUE TITLE
valid_keys for EasyMP4

### ISSUE THREAD

**Issue by brokkr** [quodlibet/mutagen#331]
EasyId3 has a helpful `valid_keys` dictionary for reference. It would be nice to have the same for EasyMP4. AFAICT the only way to get valid keys for EasyMP4 at the moment is to a) assume that the keys are the same as EasyID3 or b) look up the [source code](https://github.com/quodlibet/mutagen/blob/master/mutagen/easymp4.py#L229).

**Comment by lazka** [comment]
Both EasyID3/EasyMP4 have "Set", "Get", "Delete" and "List" properties, mapping key patterns to functions.

The "valid_keys" property would be equivalent to "Get" in both classes.

This could be documented more, but I don't really want to advertise the internals of the easy interfaces more.
