### ISSUE TITLE
can't add_tags to MP4?

### ISSUE THREAD

**Issue by elelay** [quodlibet/mutagen#334]
When trying to add tags to a downloaded MP4, I get an `AttributeError: 'MP4Tags' object has no attribute '_padding'`.
The code is [part of gPodder](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/tagging.py#L77) but here is a reproducible example:

```
>>> import mutagen
>>> f=mutagen.File("white noise.mp4", easy=True)
>>> f
{}
>>> f.info.pprint()
'MPEG-4 audio (AAC LC), 5.06 seconds, 96392 bps'
>>> f.tags
>>> f.add_tags()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/mutagen/mp4/__init__.py", line 1088, in add_tags
    self.tags = self.MP4Tags()
  File "/usr/lib/python3.6/site-packages/mutagen/easymp4.py", line 45, in __init__
    self._padding = self.__mp4._padding
AttributeError: 'MP4Tags' object has no attribute '_padding'
>>> f.tags['album'] = 'Hello'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object does not support item assignment
```
Video is at croco.elelay.fr/dropbox/white%20noise.mp4 (http)

python 3.6.3
ArchLinux
mutagen 1.39

**Comment by lazka** [comment]
Thanks.

Workaround:

```
from mutagen.mp4 import MP4Tags
MP4Tags._padding = 0
```

(This value is only used during testing, so it's unlikely to be a problem in the future)

**Comment by elelay** [comment]
great, thanks for the quick fix and workaround!
