### ISSUE TITLE
terminal application

### ISSUE THREAD

**Issue by paul-mesnilgrente** [quodlibet/mutagen#335]
Hi,

first thank you for your work, I began to use the command line program and I love the simplicity that it was to clean up music library.

I have looked into your documentation and your README, afaik there is no terminal application which uses your python library? I am currently tempted to implement a terminal application using [ncurses](https://www.gnu.org/software/ncurses/) which would be [EasyTag](https://wiki.gnome.org/action/show/EasyTAG?action=show&redirect=Apps%2FEasyTAG) like.

All the best.

**Comment by sampsyo** [comment]
[beets](https://github.com/beetbox/beets) uses Mutagen, for what it’s worth.

**Comment by paul-mesnilgrente** [comment]
Well that is not exactly what I was looking for event if it seems good... I guess this is the only use, thank you! :)

**Comment by lazka** [comment]
There also is https://quodlibet.readthedocs.io/en/latest/guide/commands/operon.html
