### ISSUE TITLE
Pycharm issue while importing APIC class

### ISSUE THREAD

**Issue by 24Naman** [quodlibet/mutagen#336]
-> from mutagen.id3 import ID3, APIC

when APIC is imported from the package mutagen.id3, Pycharm issues an error "Unresolved reference 'APIC'" as it is not declared in the '&#x5f;&#x5f;all&#x5f;&#x5f;' variable.

**Comment by lazka** [comment]
What's in `__all__` shouldn't matter here. My guess is that it can't detect the reference due to the code adding them with `globals()[f] = ...`

We could just list them all there explicitly (and add a test to the test suite that checks that all are there)

**Comment by 24Naman** [comment]
It was just a guess because when I checked the source it was not there and somebody has suggested that pycharm read __all__ variable for imports

**Comment by lazka** [comment]
Thanks for the report. If there are other things PyCharm doesn't like please report them.

**Comment by rlindner81** [comment]
I came across this issue today and I would not agree that this is a pycharm issue. It can resolve the origin of these imported classes just fine. The inspector gives a "weak" warning because it considers these classes _protected_ and so they should not be accessed for regular usage.
> This inspection warns if a protected member is accessed outside the class, a descendant of the class where it's defined or a module.

Going back to a PEP you can see why they would think that
https://www.python.org/dev/peps/pep-0008/#id50
> To better support introspection, modules should explicitly declare the names in their public API using the `__all__` attribute. Setting `__all__` to an empty list indicates that the module has no public API.

**Comment by lazka** [comment]
I think there is a misunderstanding here. This is not a pycharm issue, and these fields are/were public. They were just made pubic in a non-statically analyzable manner.

**Comment by rlindner81** [comment]
Ah, you are right. I had not seen that you closed the issue via a commit that enables proper static analysis... 

Still, as I wrote, an inspector (probably based on that PEP) still marks example code from your docs as slightly faulty.
https://mutagen.readthedocs.io/en/latest/user/id3.html
![example](https://user-images.githubusercontent.com/9608015/66421709-aa575980-ea08-11e9-8319-71c89b6e1519.png)

**Comment by lazka** [comment]
Ah, right, good point. I've created #397 for this.
