### ISSUE TITLE
Support pathlib.Path objects for paths

### ISSUE THREAD

**Issue by nvllsvm** [quodlibet/mutagen#337]
The [pathlib](https://docs.python.org/3/library/pathlib.html) module was added to the standard library in Python 3.4. The expected behavior is to be able to path either a string or a `pathlib.Path` object when referencing a file or directory. For example, this behavior is demonstrated in `open`, `gzip.open`, and `os.walk`.

**Example expected behavior in mutagen:**
```
import pathlib
from mutagen.id3 import ID3

path = pathlib.Path('somefile.mp3')
audio = ID3(path)
```

**Workaround:**
Casting the ``pathlib.Path``object as as a string.
```
import pathlib
from mutagen.id3 import ID3

path = pathlib.Path('somefile.mp3')
audio = ID3(str(path))
```

**Comment by lazka** [comment]
Supporting  `__fspath__` would make this work as well for 3.6+ (http://legacy.python.org/dev/peps/pep-0519/). Would that work for you?
