### ISSUE TITLE
mutagen.mp4.MP4StreamInfoError: not a MP4 file

### ISSUE THREAD

**Issue by ayeteng** [quodlibet/mutagen#340]
Hi all,

I use the mutagen.mp4 to read the MP4 file but it shows up 'not a MP4 file' error.

```
Sams-iMac:new sam$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mutagen.mp4 import MP4
>>> ff = MP4('MM-trading.mp4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/mutagen/mp4/__init__.py", line 1060, in load
    self.info.load(atoms, fileobj)
  File "/Library/Python/2.7/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mutagen/mp4/__init__.py", line 932, in load
    raise MP4StreamInfoError("not a MP4 file")
mutagen.mp4.MP4StreamInfoError: not a MP4 file
```

MP4 file information:
File: /Users/sam/Movies/MM-trading.mp4
Size: 150.4 MB
Format: MPEG-2 transport stream format
Programs count: 1
Stream count: 2
Duration: 00:13:27
Bit rate: 1562 kb/s

Stream 0
Type: video
Codec: h264
Codec profile: Constrained Baseline
FourCC: [27][0][0][0]
Duration: 00:13:27
Width: 960
Height: 540
Sample aspect ratio: 1:1
Display aspect ratio: 16:9
Pixel format: yuv420p
Frame rate: 29.98 fps

Stream 1
Type: audio
Codec: aac
FourCC: [15][0][0][0]
Duration: 00:13:27
Bit rate: 151 kb/s
Sample rate: 44100 Hz
Sample format: s16
Channel: 2
Meta info:
    language: eng

Does mutagen support aac audio encoding as in mp4 file?

**Comment by lazka** [comment]
It does, "MPEG-2 transport stream format" suggests that it's not an MP4

**Comment by ayeteng** [comment]
Oh! That explain everything. Thanks. Is it possible to have tag in MPEG-2 format video? I checked and find the tag only appear in mp3 and mp4.

**Comment by lazka** [comment]
I can't find anything, not sure... Wikipedia suggests VLC can handle it, so maybe it does tagging too.

**Comment by lazka** [comment]
If some support for this file type is something you need, please say so and maybe include why you would like it and what you want to use it for.

If not we can close this issue.

**Comment by ayeteng** [comment]
yes. Let me close this case. The mpeg-2 stream is not suitable for MP4 file.

Thank you for your help!
