### ISSUE TITLE
How can I separate the media data from the metadata?

### ISSUE THREAD

**Issue by danielquinn** [quodlibet/mutagen#343]
The documentation is quite thorough regarding how to read and write metatadata, which is wonderful, but only half of what I'm trying to do.

For my project, I need to generate a cryptographic signature of the raw media file (sans metadata) and after a few hours tinkering with mutagen (and a few other options) I'm still not sure of how to do this.

As a means of further explanation, I would refer you to Pillow, which has a `.tobytes()` method on its `Image` class.  This method returns the raw image data and *not* the EXIF layer.  Surely this must be possible for other formats like MP3?  Poking around in the Mutagen codebase, I see the creation of headers and moving around of bytes, but I can't quite figure out how to do this for myself.

Is something like this possible with Mutagen?  The following code is my best (failed) attempt:

```python
from io import BytesIO
from mutagen.mp3 import MP3

tmp = BytesIO()
original = MP3("/path/to/test.mp3")
original.delete()
original.save(tmp)

signature = generate_signature(tmp)
```

---

As an update, with the following code I was able to generate a new, playable copy of the file with cleared ID3 tags, but somehow *the new file is larger than the original*:

```python
from io import BytesIO
from mutagen.mp3 import MP3
from hashlib import md5

tmp = BytesIO()
with open("tests/data/test.mp3", "rb") as f:
    tmp.write(f.read())
tmp.seek(0)
print(md5(tmp.read()).hexdigest())
tmp.seek(0)
mp3 = MP3(tmp)
mp3.clear()
mp3.save(tmp)
tmp.seek(0)
print(md5(tmp.read()).hexdigest())
tmp.seek(0)
with open("tests/data/test-changed.mp3", "wb") as f:
    f.write(tmp.read())
```

Obviously this isn't ideal, since:

1. The new file is somehow larger (?)
2. It creates a copy of the file in memory
3. The new file doesn't appear to be the audio only, as there's still some ID3 header stuff in there.

Any help you might be able to provide would be appreciated.

**Comment by lazka** [comment]
`mp3.tags.delete(tmp)` (not save after) should get rid of the tag. `clear()` only removes all id3 frames and it will not shrink much because of the tag padding.

In general separating audio from the tags is not possible for all formats without demuxing, and mutagen just focuses on meta data.

**Comment by danielquinn** [comment]
That's very helpful, thank you!  I think this is will get me started.  Thanks again, and if you're interested in the project, [here it is](https://github.com/danielquinn/pyletheia).

**Comment by lazka** [comment]
ok :) Thinking of attack vectors here, one could embed an mpeg stream in the id3 tag padding, which would make players just searching for a mpeg frame sync and not skipping tags play the wrong content.

**Comment by danielquinn** [comment]
Yeah I've been tinkering with the options for extracting the "real" content and I'm leaning toward just pushing everything through `ffmpeg -i infile.mp3 -vn -codec:a copy -map_metadata -1 -f mp3 -` instead.  This way, Mutagen is left to do what it does best: write metadata and I can offload worries like the above to more robust software like ffmpeg.
