### ISSUE TITLE
MP4 stik & rtng bug

### ISSUE THREAD

**Issue by gotcha9999** [quodlibet/mutagen#349]
Writing of stik and rtng values doesn't work correctly.

Example:

You have a correct tagged MP4 audio file with stik = 1 (Normal) and rtng = 1 (Explicit) and the 
output from AtomicParsley is
    Atom "stik" contains: Normal
    Atom "rtng" contains: Explicit Content

After saving this file with mutagen you have
    Atom "stik" contains: 1
    Atom "rtng" contains: 1

OK (from Mp3Tag):
```
00 00 00 19			Atom Length: 25
73 74 69 6B			Atom Name: "stik"
00 00 00 11			Atom Length: 17
64 61 74 61			Atom Name: "data"
00 00 00 15			Atom Version & Flags
00 00 00 00			4 Bytes Null Space
01				1 -> Normal/Music
```

Wrong length (using mutagen):
```
00 00 00 1A			Atom Length: _26_
73 74 69 6B			Atom Name: "stik"
00 00 00 12			Atom Length: _18_
64 61 74 61			Atom Name: "data"
00 00 00 15			Atom Version & Flags
00 00 00 00			4 Bytes Null Space
00 01				<- wrong!
```

**Comment by lazka** [comment]
confirmed, thanks
