### ISSUE TITLE
Error when returning a "None" value in EasyID3

### ISSUE THREAD

**Issue by Coonicon09** [quodlibet/mutagen#361]
When I try to get the code for album artist from MP3 files I encountered this error when no album artist is present:

```
Traceback (most recent call last):
  File "/home/xxx/PythonProjects/yyy/cleanup.py", line 7, in <module>
    audio = get_tag(file)
  File "/home/xxx/PythonProjects/yyy/classes/mp3_tags.py", line 8, in get_tag
    albumartist = audio['albumartist'][0]
  File "/home/xxx/PythonProjects/venv/yyy/lib/python3.6/site-packages/mutagen/easyid3.py", line 213, in __getitem__
    return func(self.__id3, key)
  File "/home/xxx/PythonProjects/venv/yyy/lib/python3.6/site-packages/mutagen/easyid3.py", line 121, in getter
    return list(id3[frameid])
  File "/home/xxx/PythonProjects/venv/yyy/lib/python3.6/site-packages/mutagen/_util.py", line 536, in __getitem__
    return self.__dict[key]
KeyError: 'TPE2'
```

Can someone point me to a solution?
The code works perfectly when an album artist is present.

**Comment by lazka** [comment]
Depends on what you want to do. It implements a dict like interface so it raises if a key isn't present, like `{}['abumartist']`

**Comment by Coonicon09** [comment]
Basicly I am cleaning up my rather big (500GB easy) iTunes collection. I would also like to do some housekeeping and retagging.
Among other changes this I would like it that if there is no 'Album Artist' it becomes the same as the song artist from that album.
So I have a script that collects every file from the directory and then basicly does:
```
for file in filelist:
    audio = EasyID3(file)
    title = audio['title'][0]
    artist = audio['artist'][0]
    albumartist = audio['albumartist'][0]
    album = audio['album'][0]
```
When there is an albumartist present, no problem. When it's not, the file crashes. I want to know if I can get around this and substitute for None.
I hope this all makes sense, English is not my native language

**Comment by lazka** [comment]
```
if 'albumartist' in audio:
    albumartist = audio['albumartist'][0]
else:
    albumartist = None
```

**Comment by Coonicon09** [comment]
I feel really stupid I didn't think of something like that.

**Comment by bobo71dream** [comment]
albumartist = audio.get('albumartist'[0], [""])
