### ISSUE TITLE
pylint warning for save() methods

### ISSUE THREAD

**Issue by DionisieS** [quodlibet/mutagen#363]
First of all, this issue is present on my pc (might not be for others). I use VS Code and KDE Neon 5.14 and when I have this `audioFile.save(v2_version=3)` in my code the `audioFile` gets linted (idk if that's the correct word). The code still runs though. In the "Problems" tab it says `[pylint] E1120:No value for argument 'filething' in method call [E1120] (31,1)`

I do not have any "filething" in my code and I do not know why this happens. Heck, it might not even be mutagen's fault.

**Comment by lazka** [comment]
Not sure if we can do anything here, but worth having a look. Thanks for the report!

**Comment by lazka** [comment]
Can be fixed :)
