### ISSUE TITLE
Mutagen fails to extract the song name

### ISSUE THREAD

**Issue by Carmina16** [quodlibet/mutagen#365]
Mutagen fails to extract the song title from the attached file. Both FFmpeg and GStreamer work OK.

[test2.zip](https://github.com/quodlibet/mutagen/files/2601913/test2.zip)

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
This is again a case of #192 where Windows corrupts id3v2.4 tags.

**Comment by lazka** [comment]
Closing as a duplicate. Thanks for the example file!
