### ISSUE TITLE
Does it can extract the bytes data from a mp3 file using mutagen?

### ISSUE THREAD

**Issue by Bodemon** [quodlibet/mutagen#368]
How do I use mutagen deal with the byte data form a mp3 file which received from front-end?

**Comment by lazka** [comment]
```
from io import BytesIO
from mutagen.mp3 import MP3

MP3(BytesIO(data))
```

**Comment by Bodemon** [comment]
Thank you very much, and  I was so .....  .....

**Comment by Bodemon** [comment]
> ```
> from io import BytesIO
> from mutagen.mp3 import MP3
> 
> MP3(BytesIO(data))
> ```

Thank you very much, and I was so ..... .....

**Comment by Bodemon** [comment]
@lazka Thank you very much....

**Comment by lazka** [comment]
Some more details here: https://mutagen.readthedocs.io/en/latest/user/filelike.html
