### ISSUE TITLE
Cannot access pictures from Ogg Theora file

### ISSUE THREAD

**Issue by EliotBerriot** [quodlibet/mutagen#370]
I've got the following audio file (audio is truncated):     https://files.eliotberriot.com/f/ee393e4d45/?raw=1

When trying to open it with `mutagen.File(thefile)`, mutagen detects it as an OggTheora file (I've used a debugger [here](https://github.com/quodlibet/mutagen/blob/master/mutagen/_file.py#L287-L292) to confirm that:

```
print(scores)
> [((2, 'OggTheora'), <class 'mutagen.oggtheora.OggTheora'>), ((1, 'OggVorbis'), <class 'mutagen.oggvorbis.OggVorbis'>), ((0, 'WavPack'), <class 'mutagen.wavpack.WavPack'>)]
```

However, accessing the embedded images, [as described in the documentation](https://mutagen.readthedocs.io/en/latest/user/vcomment.html#embedded-images) does not yield any result:

```python
import mutagen
path = 'with_cover.ogg'
data = mutagen.File(path)
print(data.get('metadata_block_picture'))
> None
```

However, if I force the file to be parted as an OggVorbis file, I can access the image data successfully:

```python 
import mutagen.oggvorbis
path = 'with_cover.ogg'
data = mutagen.oggvorbis.OggVorbis(path)
print(data.get('metadata_block_picture'))
> ['AAAAAwAAAAppbWFnZS9qcGVnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5t/9j/4AAQSkZJRgABAQEBLAEsAAD/4……………']
```

So I'm wondering: is the guessing wrong here? Or maybe embedded pictures are not supported for OggTheora files in mutagen?

Anyway, I'll try to dig into that, but I wanted to open the issue anyway since people around here may have an idea ;)

**Comment by lazka** [comment]
Yeah, we prefer tags of the theora stream because https://wiki.xiph.org/index.php?title=VorbisComment

> VorbisComments are typically encoded as the second packet in a codec stream. When VorbisComments are included in the first (ie. Theora) stream of an Ogg Theora file, they are assumed to cover all streams in the multiplexed group. [2] 

> So I'm wondering: is the guessing wrong here? Or maybe embedded pictures are not supported for OggTheora files in mutagen?

With the above in mind I'd say the guess is correct. Both streams support all tags, so this is just some software preferring the vorbis stream over the theora stream when writing tags.

**Comment by lazka** [comment]
Thought I'd have to check if it really is the first stream here, since our guessing is just string matching... so maybe it's a bug :)

**Comment by EliotBerriot** [comment]
> With the above in mind I'd say the guess is correct. Both streams support all tags, so this is just some software preferring the vorbis stream over the theora stream when writing tags.

Ok, that makes sense. I'm using Musicbrainz Picard for the tagging / cover embedding, so the issue is likely coming from here.

Anyway, thank you for your quick answer, I'll probaly handle this case manually in my software!

**Comment by lazka** [comment]
> Thought I'd have to check if it really is the first stream here, since our guessing is just string matching... so maybe it's a bug :)

No, the theora stream is first, so no bug (at least not in this case)
