### ISSUE TITLE
Wrong processing of multiple values stored in TYER in id3v2

### ISSUE THREAD

**Issue by Baz93** [quodlibet/mutagen#380]
Here is how to reproduce:

```python
from mutagen.id3 import ID3, TYER

with open('a.mp3', 'w'):
    pass
tags = ID3()
tags['TYER'] = TYER(text=['2000', '2000', '2000'])
tags.save('a.mp3', v2_version=3, v23_sep=None)
tags = ID3('a.mp3')
print(tags)

# outputs this:
# {'TDRC': TDRC(encoding=<Encoding.LATIN1: 0>, text=[''])}
```

**Comment by lazka** [comment]
Thanks

**Comment by Baz93** [comment]
Forgot to mention that it is a problem of tag reading, not writing. I.e. if you write the tags via Mp3tag, mutagen won't be able to read them either. Though other applications will read it properly.

**Comment by dguyton** [comment]
Does this problem only occur when the values are duplicates? Does it also occur with multiple, identical frames (e.g. 3x TYER frames with identical '2000' values)?

**Comment by Baz93** [comment]
No. It does not matter if the values are equal or not. So this code
``` python
tags = ID3()
tags['TYER'] = TYER(text=['2000', '2001', '2002'])
tags.save('a.mp3', v2_version=3, v23_sep=None)
tags = ID3('a.mp3')
print(tags)
```
Outputs also this: `{'TDRC': TDRC(encoding=<Encoding.LATIN1: 0>, text=[''])}`

if I store multiple TYER frames, it also works strange. This code
``` python
tags = ID3()
tags['TYER1'] = TYER(text=['2000'])
tags['TYER2'] = TYER(text=['2000'])
tags['TYER3'] = TYER(text=['2000'])
tags.save('a.mp3', v2_version=3, v23_sep=None)
tags = ID3('a.mp3')
print(tags)
```
Outputs also this: `{'TDRC': TDRC(encoding=<Encoding.LATIN1: 0>, text=['2000'])}`
Which is ok, I guess. And this code
``` python
tags = ID3()
tags['TYER1'] = TYER(text=['2000'])
tags['TYER2'] = TYER(text=['2001'])
tags['TYER3'] = TYER(text=['2002'])
tags.save('a.mp3', v2_version=3, v23_sep=None)
tags = ID3('a.mp3')
print(tags)
```
Outputs also this: `{'TDRC': TDRC(encoding=<Encoding.LATIN1: 0>, text=[''])}`

**Comment by lazka** [comment]
See #385
