### ISSUE TITLE
Question about iTunes atom support

### ISSUE THREAD

**Issue by sakinwus** [quodlibet/mutagen#381]
Hi,
I was wondering if the MP4 class was capable of writing these iTunes related atoms ‘plID’, ‘cnID’, ‘geID’, ‘atID’, ‘sfID’, ‘cmID’, ‘akID’?

At the moment I get a "mutagen.mp4.MP4MetadataValueError: value out of range:" whenever I try to edit the 'sfID' for instance.

Thank You

**Comment by lazka** [comment]
They should work, we have some tests at least: https://github.com/quodlibet/mutagen/blob/e393df5971ba41ba5a50de9c2c9e7e5484d82c4e/tests/test_mp4.py#L646

**Comment by sakinwus** [comment]
Hmm I see. It might be a syntax issue on my end then.
This is how i'm doing it right now

```
f = 'file.m4a'
tags = MP4(f)
tags['sfID'] = '143469'
```
mutagen.mp4.MP4MetadataValueError: value out of range: '143469'

This works if I use this 'rting' field but not for sfID.

**Comment by lazka** [comment]
Try:

```
f = 'file.m4a'
tags = MP4(f)
tags['sfID'] = [143469]
```

**Comment by sakinwus** [comment]
Oh that seemed to have worked, thanks!
Question is there a way to loop to edit multiple files?

**Comment by lazka** [comment]
No, you'd have to do that manually.

**Comment by sakinwus** [comment]
Gotcha, thanks for the help!
