### ISSUE TITLE
text frames end with a trailing null for id3v2 frames

### ISSUE THREAD

**Issue by rupaschomaker** [quodlibet/mutagen#384]
If I use mid3v2 to modify the id3 tags of an mp3 file, the text fields (artist and album are the ones I'm working with) end with a null value.  

I've tried reading the files using python libs:
- TinyTag
- mp3_tagger

LazyLibrarian uses the TinyTag lib to parse this info and it has issues with the trailing null.

Of course, mutagen-inspect has no issues and does not show a trailing null...  Help?

**Comment by lazka** [comment]
See #379 for a related issue

**Comment by dguyton** [comment]
Seems more like an issue with LazyLibrarian, no? If it is parsing a null character and presenting it as a space when the null appears at EOL. Why not simply drop the null? What if a string only contains null? Does it behave that way as well? Seems odd to me and not a mid3v2 bug. Just my 2 cents FWIW. :)

**Comment by lazka** [comment]
Yeah, it's unlikely that we will change things on our side (see the linked issue for why)

If you find a more widely used program which has similar problems please report them to us.

**Comment by rupaschomaker** [comment]
I'm not going to argue against closing, just to complete some research.   LazyLibrarian actually uses the null - it is just using the set of bytes returned by the python TinyTag tagging library.  I looked at a sampling of id3 tools in unbuntu:
apt install id3v2 id3tool eyed3 id3 mp3info

Viewing files written by mutagen:

id3v2: no null
id3tool: no null (not sure it does id3v2 though)
eyed3: no null
id3: no null
mp3info: no null

If any of these are C based, they are probably just treating the null as a end of string, so the fact we don't see the null in the output doesn't mean they don't get the null on reading the field from the file.

In any case, at least using these tools the null is treated right.  The python based ones seem to have interpreted the std differently so I'll ask there.  

Thanks.

**Comment by dguyton** [comment]
I'm thinking @rupaschomaker may be right. Could be how the parser handles null at end of string, since I believe Python treats it literally (i.e. "I presume you wanted a null at the end of your string.") and does not use any sort of end-of-string characters (thank G_d) IIRC.

I've done a bit of QA in C++ but not hardcore programming. I have not programmed in C for over 25 years, so can't comment there. :) Sounds plausible tho.
