### ISSUE TITLE
FLAC CORRUPTED AFTER ADDED IMAGES

### ISSUE THREAD

**Issue by An0nimia** [quodlibet/mutagen#387]
I am trying to add a pic to a specify flac file, mutagen does his job, but if I try to do 'flac -t file-name.flac' it gives me this error: ERROR while decoding data
                                  state = FLAC__STREAM_DECODER_ABORTED.
For some reasons adding images in flac corrupts the song here is the code
```
tag = FLAC(song)
tag.delete() #also if a delete this line of code gives me error
images = Picture()
images.type = 3
images.data = data['image'] #bytes obv
tag.add_picture(images)
tag.save()
```
But if I try to add images 143x41 resolution the flac is ok I tried to find out some connection, but without results.

**Comment by lazka** [comment]
Can you send me the files you used so I can try to reproduce the issue? -> reiter.christoph@gmail.com

thanks

**Comment by An0nimia** [comment]
Files sent.

**Comment by lazka** [comment]
I can't reproduce the issue using the following code:

```python
from mutagen.flac import FLAC, Picture

song = FLAC("song.flac")
song.delete()
pic = Picture()
image = Picture()
image.type = 3
image.data = open("eminem-berzerk.jpg", "rb").read()
song.clear_pictures()
song.add_picture(image)
song.save()
```

```python
>>> mutagen.version_string
'1.41.2'
```

```bash
$ flac --version
flac 1.3.2
```

**Comment by An0nimia** [comment]
Advertising I am going to write something that you could feel angry.
The problem wasn't with mutagen but with file interaction. The flac has been created writing something in binary mode and after this process I didn't close the file with the method .close. So when I used FLAC function to open a file which was using another process. Did I explain myself? Sorry for my English and thanks to have wasted your time for me :)

**Comment by lazka** [comment]
no problem. glad you got it working :)
