### ISSUE TITLE
Import mp3 fail. No modules are not found!

### ISSUE THREAD

**Issue by Lakshmana219** [quodlibet/mutagen#395]
Here the message is:-

    from mutagen.mp3 import MP3
ImportError: No module named mp3

I tried importing other modules like mp4, ID3... facing the same issue.

I  installed through pip and even installed with setup file downloaded from the official git hub.

And the environment is, Hadoop cluster-Linux.

Please help me soon.

**Comment by lazka** [comment]
No idea. Maybe you have a file named "mutagen.py" in your directory which you load by accident?
