### ISSUE TITLE
How to get mutagen 1.39 on Ubuntu 18.04.3 LTS?

### ISSUE THREAD

**Issue by keunes** [quodlibet/mutagen#399]
I am having an issue with saving changes to files stored on my samba home server, in Picard. [The ticket I created](https://tickets.metabrainz.org/browse/PICARD-1627) with that project was closed because the issue supposedly with Mutagen 1.39. However, I am running Ubuntu 18.04.3 LTS and I already have the 'latest version' installed:
```
sudo apt install --only-upgrade python3-mutagen
Reading package lists... Done
Building dependency tree 
Reading state information... Done
python3-mutagen is already the newest version (1.38-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

Is there any way for me to get Mutagen 1.39 installed on my system? I didn't see a project ppa that I could install.

**Comment by lazka** [comment]
There is https://launchpad.net/~lazka/+archive/ubuntu/ppa (maintained by me). But I guess I forgot to update it to the latest release. I'll do that later.

**Comment by keunes** [comment]
Ah, that worked, thanks! Is it an idea to include a reference to the PPA in the docs? Searching for ppa currently doesn't yield any result.

**Comment by lazka** [comment]
The PPA is mainly there for quodlibet, since it needs a newer mutagen than is available in older Ubuntu releases.

In general I don't think it's a good idea to let users update system libraries through PPAs unless there is a good reason because it affects all depended system packages. It's better to use virtual envs and install it there through pip, or install it with "pip install --user" which is at least easy to revert if problems arise. So that's why I don't want to recommend it in the docs really.

**Comment by keunes** [comment]
Hi @lazka, thanks for your reply. I'm not very technical so I don't know about virtual environments and pip really. I understand though it's better to rely on system defaults. But if that means the programme I'm using doesn't work, the benefit is outweighed by the downside.

It's maybe a matter of target audiences: I'm relying (without me even knowing, until a week ago) on mutagen to tag my music library. I don't know what 'pip' is and if I do `pip install --user` I will get the latest mutagen version that works with Picard. I imagine many others using Picard don't know this either. To come to my point: PPA's are more noob-friendly, but only you know if you actually want to target this audience group. I just wanted to flag this up in the context of documentation decision :)

**Comment by keunes** [comment]
I guess, if you don't want to mention the ppa in the documentation, this issue can be closed. Many thanks for your help! :)

**Comment by lazka** [comment]
>  (the Picard maintainer/developer was also thinking to include mutagen in their ppa, as to avoid issues)

Ah, yes, if their PPA depends on a newer version that's definitely a good idea. You can even copy packages from one PPA to another in the launchpad UI.

**Comment by lazka** [comment]
(I've updated the PPA now.  Might take a few minutes)
