### ISSUE TITLE
Support Opus

### ISSUE THREAD

**Issue by lud4ik** [quodlibet/mutagen#401]
In web default audio record settings are webm container with Opus codec
```
audio/webm
Codec Name - opus
Codec Long Name - Opus (Opus Interactive Audio Codec)
```
We checked and it's not supported by this library to validate the header of file.
OggOpus and Opus are not the same.
Is it possible to add support for Opus?

**Comment by phw** [comment]
Isn't this basically a duplicate of #396?

And WebM is a subset of #3

**Comment by lud4ik** [comment]
any chance to be supported?

**Comment by lazka** [comment]
Closing as a duplicate of #396

I'm sorry that it's not supported yet, but my time is limited.

**Comment by phw** [comment]
@lud4ik I have used in some code https://github.com/QBobWatson/python-ebml , it seems to be very solid.

**Comment by lud4ik** [comment]
> @lud4ik I have used in some code https://github.com/QBobWatson/python-ebml , it seems to be very solid.

It is in alpha by pypi. I can't use it in prod((

**Comment by ffe4** [comment]
@lud4ik the package on PyPI is another package.
