### ISSUE TITLE
[RFC] Drop Python 2 support

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#410]
I haven't put much thought into it yet, but we should have some plan for when to drop support.

https://pypistats.org/packages/mutagen

Looking at the weekend drop off looks like Python 2 is mostly used in company environments.

Are there any major users of mutagen which haven't been ported yet?

@phw any blockers you know of?

**Comment by lazka** [comment]
If we drop support I'll try to backport bugfixes to the last Python 2 supporting release if requested.

**Comment by lazka** [comment]
@hugovk thanks for pypistats!

I'm wondering if it would be possible to also show the pip version used? We can easily drop Python 2 support without breaking things for users by setting `python_requires`, but that's only respected by pip >= 9.0, so for users of older pip versions dropping Python 2 support will break their install.

**Comment by hugovk** [comment]
You're welcome!

You can't see pip version with pypistats, but you can probably get it via the PyPI stats on BigQuery. 

pypinfo is a good way, perhaps something like `pypinfo mutagen installer-version` will do it. (I'm out of free quota right now.) https://github.com/ofek/pypinfo/ 

pip 9 is now [3 years old](https://pypi.org/project/pip/#history). Many projects I've seen aren't too worried about old pip, but if it's a concern (and good to find stats first), https://python3statement.org/practicalities/ has some tips like printing an error in `setup.py` for Python 2.

**Comment by lazka** [comment]
ok, thanks, I'll try that.

ubuntu 16.04 still has pip 8.1.1, which is what I'm worried about.

**Comment by lazka** [comment]
puh, using bigquery used to be easier...

```
> pypinfo --all -l 30 mutagen installer installer-version
| installer_name | installer_version | download_count |
| -------------- | ----------------- | -------------- |
| pip            | 18.1              |         33,181 |
| pip            | 9.0.1             |         14,106 |
| pip            | 19.2.3            |         13,957 |
| pip            | 19.0.3            |          6,590 |
| None           | None              |          3,079 |
| pip            | 19.3              |          2,871 |
| pip            | 19.3.1            |          2,231 |
| pip            | 19.1.1            |          1,609 |
| bandersnatch   | 3.6.0             |            894 |
| pip            | 9.0.3             |            649 |
| pip            | 19.2.2            |            626 |
| pip            | 10.0.1            |            554 |
| Browser        | None              |            514 |
| pip            | 8.1.1             |            279 |
| pip            | 19.2.1            |            258 |
| pip            | 18.0              |            199 |
| setuptools     | 41.4.0            |            168 |
| bandersnatch   | 2.0.0             |            165 |
| pip            | 9.0.2             |            163 |
| setuptools     | 41.2.0            |            155 |
| setuptools     | 28.8.0            |            145 |
| bandersnatch   | 3.4.1             |            130 |
| bandersnatch   | 3.5.0             |            123 |
| pip            | 19.1              |            111 |
| setuptools     | 40.8.0            |            111 |
| pip            | 1.5.4             |            111 |
| setuptools     | 39.0.1            |            101 |
| pip            | 19.0.1            |             96 |
| setuptools     | 41.0.1            |             78 |
| pip            | 7.1.2             |             75 |
| Total          |                   |         83,329 |
```

so, assuming the data is correct, this would only break 0.5% of all installs, which seems fine to me.

**Comment by phw** [comment]
From my point of view it would be fine to drop support. The existing versions would still be around, so users of Python 2 have a way to handle that. Some thoughts on the process:

1. This probably would warrant a version change to 2.0
2. I personally would probably do a last release 1.43 with changes currently lined up, in this release announce Python 2 support as deprecated and afterwards remove Python 2 support from the sources

**Comment by lazka** [comment]
re (1), we are not breaking API, so that would be confusing to Python 3 users imo. re (2), sounds good.

**Comment by lazka** [comment]
The 1.43.0 release now has universal wheels on pypi, requires setuptools and includes a python version requirement. So dropping Python 2 should be easy now.

**Comment by lazka** [comment]
Done in 36de51abd2

**Comment by lazka** [comment]
I made a new Python 3 only release
