### ISSUE TITLE
 Timeout while processing an mp4 file

### ISSUE THREAD

**Issue by jvoisin** [quodlibet/mutagen#424]
When running the following python script with the [attached file]( https://github.com/quodlibet/mutagen/files/3964120/timeout-e529178f7e1a634f9aa508b72c8a04451ffe6b516e9bdc7ec10a312076158c03.zip), mutagen goes into an infinite loop:

```python
import mutagen, sys

mutagen.File(sys.argv[1])
```

```python3
$ python3 ./mutest.py timeout-e529178f7e1a634f9aa508b72c8a04451ffe6b516e9bdc7ec10a312076158c03
…
```

It seems that the fix could be to check if length is superior to zero [here]( https://github.com/quodlibet/mutagen/blob/cb363c1cc24fd1f5f57dfe187730fabd305f5191/mutagen/mp4/__init__.py#L610).

This issue is similar to #416

**Comment by phw** [comment]
This got fixed in #429
