### ISSUE TITLE
[question] is there any version of mutagen where easymp3 expose TIT3 as subtitle?

### ISSUE THREAD

**Issue by elelay** [quodlibet/mutagen#438]
A user suggested an improvement to gPodder's tagging extension, which is based on mutagen (see https://github.com/gpodder/gpodder/issues/737).
It turns out it uses  `audio.tags['subtitle']` and `audio.tags['comments']` where `audio` is an easymp3 object. That doesn't work with latest mutagen.

He sent me his *local* version of mutagen, which indeed contain tag mappings `TIT3` to `subtitle` and `COMM` to `comments`. This is the only difference with commit b15f1f4ba080a12667a7aa1002e361ece84f98d9.

To your knowledge, was there a version of mutagen (maybe in a branch) where this was true?

**Comment by lazka** [comment]
easyid3 hasn't changed in ages and the TIT3 mapping is there for 11 years according to git, and I don't remember branches. Not sure how this can happen right now, but maybe I'm missing something..

https://github.com/quodlibet/mutagen/blob/ff2e64cfe78dd7867ac11738d6c1ff634348fca0/mutagen/easyid3.py#L474

**Comment by elelay** [comment]
ok, the user modified the `easyid3.py` file locally...

Would it make sense to add mapping?

    "COMM": "comments",
    "TIT3": "subtitle",

**Comment by lazka** [comment]
I don't really want to change easyXXX too much at this point as others might depend on the current mapping. It should be possible to add your own mapping by calling `EasyID3.RegisterTextKey("TIT3", "subtitle")`

**Comment by elelay** [comment]
ok, thanks, I'll do that.

**Comment by elelay** [comment]
It works, thanks!
It's the other way round actually: `EasyID3.RegisterTextKey("subtitle", "TIT3")`.
