### ISSUE TITLE
Add fuzzing integrations

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#443]
@jvoisin has recently found various bugs through fuzzing and has reported that there are many more cases.

We should look into integrating with a fuzzer so everyone can do it and maybe we could even add it to CI.

Two fuzzers which should work for mutagen:

* https://github.com/fuzzitdev/pythonfuzz
* https://github.com/jwilk/python-afl

They both use coverage guided fuzzing.

**Comment by jvoisin** [comment]
This is what my local'n'ugly fuzzer looks like:

```python
import os
import mutagen
from pythonfuzz.main import PythonFuzz

@PythonFuzz
def fuzz(buf):
    path = '/tmp/lol'
    with open(path, 'wb') as f:
        f.write(buf)
    try:
        f = mutagen.File(path)
        if f :
            if f.tags:
                for i in f.tags.items():
                    pass
            f.delete()
            f.save()
    except mutagen.MutagenError:
        pass
    os.remove(path)

if __name__ == '__main__':
    fuzz()
```

**Comment by lazka** [comment]
Our fuzzing integration is documented here: https://github.com/quodlibet/mutagen/blob/main/fuzzing/README.rst

There are lots of issues uncovered by fuzzing that need to be looked at, so I think this can be closed.

**Comment by jvoisin** [comment]
[OSS-Fuzz is fuzzing mutagen as well](https://github.com/google/oss-fuzz/tree/master/projects/mutagen). Feel free to add your email address [here](https://github.com/google/oss-fuzz/blob/master/projects/mutagen/project.yaml) to get access to the crashes before they're derestricted.
