### ISSUE TITLE
Audiobook player not showing chapters correctly when using mutagen to edit chapters

### ISSUE THREAD

**Issue by hugoromo** [quodlibet/mutagen#451]
Hello,
When I use mutagen from Python to edit chapters of a mp3 file, some mp3 players (Voice Audiobook player for Android specifically) doesn't show the chapters corretly, it only show some chapters and in a weird order, do anyone have a clue of why this is happening?

**Comment by lazka** [comment]
No idea, sorry. A good start would be to get a file from somewhere else which _does_ show correctly and compare them, first by comparing the frames read by mutagen, and if that doesn't help on a binary level.

**Comment by hugoromo** [comment]
I am not really an expert in this matter. Could you help me out?

**Comment by lazka** [comment]
I can't really debug some android app, so not sure how I could help. If you find some other application that shows similar issues on Linux/Windows then I can have a look (assuming you send me an example file -> reiter.christoph@gmail.com)

**Comment by lazka** [comment]
Feel free to send me a file or open an issue if you can provide something I can reproduce with.
