### ISSUE TITLE
Long file name handling under Windows

### ISSUE THREAD

**Issue by djmhunt** [quodlibet/mutagen#452]
I have been having trouble opening some files with long filenames using mutagen. An example of such a file path is: D:/Dropbox/Music/George Frederick Handel/Handel  Messiah/1-08 Recitative (Alto)  Behold, A Virgin Shall Conceive  Isaiah 7 14; Matthew 1 23 - Air (Alto)  O Thou That Tellest Good Tidings To Zion  Isaiah 40 9; 60 1 - Chorus  O Thou That Tellest Good Tidings To Zion, Arise  Isaiah 40 9; 60 1.mp3'. This issue was on an up to date Windows 10 machine with Python 3.7.6.

This resulted in the error provided in full at the end. I think this is an issue with opening files in python with file paths longer than 260 characters on Windows, as described [here on stackoverflow](https://stackoverflow.com/a/60105517). The solution provided worked for me. I would like to propose including a line somewhere to modify the file path, if under windows and if long enough:
filename = '\\\\?\\' + filename.replace('/', '\\')

mutagen._util._openfile looks like a suitable place to include this, but as I am new to this codebase you might have better ideas.

Many thanks

```
AttributeError                            Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mutagen\_util.py in verify_fileobj(fileobj, writable)
     69     try:
---> 70         data = fileobj.read(0)
     71     except Exception:

AttributeError: 'MutagenError' object has no attribute 'read'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-118-2cc263994c72> in <module>
      1 
----> 2 mutagen.File(file_path)
      3 
      4 

~\Anaconda3\lib\site-packages\mutagen\_util.py in wrapper_func(*args, **kwargs)
    145                 convert_file_args(args, kwargs)
    146             with _openfile(None, filething, filename, fileobj,
--> 147                            writable, create) as h:
    148                 return func(h, *args, **kwargs)
    149 

~\Anaconda3\lib\contextlib.py in __enter__(self)
    110         del self.args, self.kwds, self.func
    111         try:
--> 112             return next(self.gen)
    113         except StopIteration:
    114             raise RuntimeError("generator didn't yield") from None

~\Anaconda3\lib\site-packages\mutagen\_util.py in _openfile(instance, filething, filename, fileobj, writable, create)
    226 
    227     if fileobj is not None:
--> 228         verify_fileobj(fileobj, writable=writable)
    229         yield FileThing(fileobj, filename, filename or fileobj_name(fileobj))
    230     elif filename is not None:

~\Anaconda3\lib\site-packages\mutagen\_util.py in verify_fileobj(fileobj, writable)
     71     except Exception:
     72         if not hasattr(fileobj, "read"):
---> 73             raise ValueError("%r not a valid file object" % fileobj)
     74         raise ValueError("Can't read from file object %r" % fileobj)
     75 

ValueError: MutagenError(FileNotFoundError(2, 'No such file or directory')) not a valid file object

```

**Comment by lazka** [comment]
Using extended paths also changes the way Windows interprets the path, so that wont work in all cases and breaks other users. You can just convert your paths to extended ones yourself before passing them to mutagen.

Anyway, since you are using Windows 10, you should reinstall Python and select the "Disable Path Length Limit" option. This should make longer paths work everywhere in Python (up to 32000)

![maxpath](https://user-images.githubusercontent.com/991986/78167146-43ae7800-744e-11ea-8edd-c3cfbd438612.jpg)

**Comment by lazka** [comment]
Ah, I guess you are not using the official installer, so you have to enable the path limit option yourself.

Google gives me this for example: https://betanews.com/2016/05/29/long-paths-windows-10/

**Comment by djmhunt** [comment]
> Ah, I guess you are not using the official installer, so you have to enable the path limit option yourself.
> Google gives me this for example: https://betanews.com/2016/05/29/long-paths-windows-10/

That is useful to know. Thank you

> You can just convert your paths to extended ones yourself before passing them to mutagen.

This works for my current use case, but if I wanted to use Quad Libet, the file just does not appear. I suspect other libraries using mutagen will have a similar problem.

> Using extended paths also changes the way Windows interprets the path, so that wont work in all cases and breaks other users. 

My hope was that it would be possible to only apply the change when necessary, i.e. wrapped in an if statement or try except, and without any performance hit per item. How and where to best do this in mutagen is my reason for opening this issue, hoping that it would be useful for others.

**Comment by lazka** [comment]
> This works for my current use case, but if I wanted to use Quad Libet, the file just does not appear. I suspect other libraries using mutagen will have a similar problem.

That's a bug in quodlibet then we'll need to fix.

**Comment by lazka** [comment]
I've filed https://github.com/quodlibet/quodlibet/issues/3335

> My hope was that it would be possible to only apply the change when necessary, i.e. wrapped in an if statement or try except, and without any performance hit per item. How and where to best do this in mutagen is my reason for opening this issue, hoping that it would be useful for others.

You can just do it before you pass paths to mutagen. I don't think this has any place in mutagen itself though.

**Comment by lazka** [comment]
Fixed in quod libet.
