### ISSUE TITLE
[Question] How to only display basic APIC information?

### ISSUE THREAD

**Issue by codenotworking** [quodlibet/mutagen#453]
I'm new to Python and Mutagen.

Here is the basic code I have:

```
from mutagen.id3 import ID3
audio = ID3(r"audio.mp3")
print(audio.pprint())
```

This outputs all of the ID3 tags being used on the MP3.  But I want to fine tune the output to only include APIC information.  I have tried `getall()`:

```
print(audio.getall("APIC"))
```

And I have tried using a `for` loop with the suggestion here ([ID3 Dict Interface](https://mutagen.readthedocs.io/en/latest/user/id3.html#id3-dict-interface)) for displaying all the frames of one type:

```
for frame in audio.getall("APIC"):
    frame
```
But I keep getting the frame hashes from the one or more attached pictures.

Is there any way to only get the the basic APIC tag information that `print(audio.pprint())` from above provides, without the other tags and without the frame hashes?

Or is there a way to display the APIC picture type?

**Comment by lazka** [comment]
The frame should have them as attributes, see https://mutagen.readthedocs.io/en/latest/api/id3_frames.html#mutagen.id3.APIC

**Comment by codenotworking** [comment]
Dumb question, since I am new to Python and Mutagen, but how would I access the attributes?  Particularly the "type" attribute?

**Comment by lazka** [comment]
`frame.type`

**Comment by codenotworking** [comment]
Thanks.  This works:

```
for frame in audio.getall("APIC"):
    frame.type
```
For multiple pictures attached to an MP3, is there a way I can access each APIC's frame?  How would I reference it?

**Comment by lazka** [comment]
The loop you are using should cycle through all APIC frames

**Comment by codenotworking** [comment]
You are correct.  I realized I could just write an `If` statement to get the information I need.  Thanks for your help.
