### ISSUE TITLE
[Question] How to modify existing ID3 tags

### ISSUE THREAD

**Issue by codenotworking** [quodlibet/mutagen#459]
I'm trying to modify existing ID3 tags in an mp3 file.

I have looked at `ID3Tags.add()` and `ID3Tags.setall()` on [https://mutagen.readthedocs.io/](https://mutagen.readthedocs.io/).

If I use `ID3Tags.delall()` and then `ID3Tags.add()`, that seems to work.
But `ID3Tags.setall()` doesn't, unless I am incorrectly using it.

I would like to get `ID3Tags.setall()` to work, since according to the aforementioned documentation, it _"Delete frames of the given type and add frames in ‘values’."_

Here's my code:
```
from mutagen.id3 import ID3
audio = ID3(r"audio.mp3")
audio.setall("WOAR", WOAR(url=[u"http://www.website.com"]))
```
But then I receive the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'WOAR' is not defined
```
I have even tried importing all of ID3 by using `from mutagen.id3 import *`, but still receive the error.

How do I use `ID3Tags.setall()` correctly?

**Comment by codenotworking** [comment]
I figured out I was uI figured out I was using `ID3Tags.setall()` incorrectly.  I re-read the method and realized `values` parameter had to be in a Python list.

The other thing I noticed is I had to import the necessary ID3 frames to get the `ID3Tags.setall()` to work: `from mutagen.id3 import ID3, COMM, WOAR`.

Is there a way I can import all the frames, without specifying them individually?

**Comment by lazka** [comment]
> How do I use `ID3Tags.setall()` correctly?

It takes a list of frames as the secont parameter: https://mutagen.readthedocs.io/en/latest/api/id3.html#mutagen.id3.ID3Tags.setall

> Is there a way I can import all the frames, without specifying them individually?

Not at the moment, but there is an issue about it: #397

**Comment by codenotworking** [comment]
Thanks.  I got `ID3Tags.setall()` working.

As for importing frames, I'll just stick to importing them individually as needed.
