### ISSUE TITLE
about the mp3 tags in old encoding

### ISSUE THREAD

**Issue by ucas010** [quodlibet/mutagen#460]
hi,dear

I have used the MP3 to get the tags of the mp3 file,
but the results are hard to understand
codes
```
from mutagen.mp3 import MP3
path='wxsm.mp3'
songFile = MP3(path)
title = songFile.tags['TIT2'].text[0]
album=songFile.tags['TALB'].text[0]
artist=songFile.tags['TPE1'].text[0]
```

results
```
>>> title
'ÎÞÐÄË¯Ãß'
>>> album
'×îÈÈ'
>>> artist
'ÕÅ¹úÈÙ'
```

coudl you please help me ?

thx

**Comment by lazka** [comment]
Do you know which encoding they use?

**Comment by ucas010** [comment]
@lazka 
this is the detail
`TIT2(encoding=<Encoding.LATIN1: 0>, text=['ÎÞÐÄË¯Ãß'])`

**Comment by lazka** [comment]
ok, with a bit of guessing and deepl helping me translate chinese I'd guess the real encoding is gb18030

```python
>>> "ÕÅ¹úÈÙ ×îÈÈ ÎÞÐÄË¯Ãß".encode("latin-1").decode("gb18030")
'张国荣 最热 无心睡眠'
```

**Comment by lazka** [comment]
My guess would be that this is using gb18030 id3v1 tags, which means there isn't much we can do. If you send me the file per mail (reiter.christoph@gmail.com) I an have another look, but no promises.

**Comment by ucas010** [comment]
@lazka 
thx,it's helpful
