### ISSUE TITLE
breaks m4a files

### ISSUE THREAD

**Issue by tcurdt** [quodlibet/mutagen#470]
I've used 

```
% mid3v2 --version
mid3v2 1.3
Uses Mutagen 1.44.0
```

to set a some tags

```
% mid3v2 -v -a "Alice In Chains" -A "Jar of Flies" -t "No Excuses" -y 1994 -T 4 ~/Desktop/test.m4a 
Writing ~/Desktop/test.m4a
No ID3 header found; creating a new tag

% mid3v2 -l ~/Desktop/test.m4a                                                        
IDv2 tag info for ~/Desktop/test.m4a
TALB=Jar of Flies
TDRC=1994
TIT2=No Excuses
TPE1=Alice In Chains
TRCK=4
```

It looks like it worked - but I can no longer play the m4a.

**Comment by lazka** [comment]
id3 tags and mp4 files aren't compatible. You can delete them again with `mid3v2 -D`

**Comment by tcurdt** [comment]
@lazka Thanks for clearing that up. I was under the impression mutagen would also allow setting metadata for m4a.

https://mutagen.readthedocs.io/en/latest/api/mp4.html

Surprised it stills writes them then.

Any pointers what else to use?

**Comment by lazka** [comment]
mutagen supports mp4 tags, but mid3v2 is just a clone of the id3v2 CLI tool.

re CLI taggers, there is AtomicParsley and operon I know of

**Comment by tcurdt** [comment]
@lazka Now I am a little confused. I thought mid3v2 is just a cli frontend to mutagen. So using mutagen as a library I could write the metadata of m4a files?

But I will also have a look at AtomicParsley - thanks for the suggestion!

**Comment by lazka** [comment]
See https://mutagen.readthedocs.io/en/latest/man/mid3v2.html for details (or `man mid3v2`)

**Comment by tcurdt** [comment]
It essentially points to https://github.com/quodlibet/quodlibet - a shame there is no full CLI to mutagen.

**Comment by tcurdt** [comment]
That said - I think it would be wise to refused tagging of m4a files in mid3v2.
