### ISSUE TITLE
Questions regarding python 2 support.

### ISSUE THREAD

**Issue by mzaman07** [quodlibet/mutagen#471]
Hi,

I'm not sure if this is the place to ask. I am working on a project called [Oppia](https://github.com/oppia/oppia) and we use this library for identifying the correct mp3 format. Recently I am working on a [feature](https://github.com/oppia/oppia/pull/9088) that uses it as a background MapReduce job in Google App Engine. 

After running the job an error is thrown via Google App Engine. 

`Traceback (most recent call last): (/third_party/gae-mapreduce-1.9.22.0/mapreduce/handlers.py:517)
 .  
 .
 .
  File "/python27/python27_lib/versions/1/google/appengine/ext/appstats/formatting.py", line 203, in _format_value
    dct = getattr(val, '__dict__', None)
TypeError: descriptor '__dict__' for 'BitrateMode' objects doesn't apply to 'BitrateMode' object
`

Upon further investigation, I found out that the appstats module in Google App Engine is throwing (line ) the error because [BitRate](https://github.com/quodlibet/mutagen/blob/9ff77790090774bc3c633f74f58a063886368a8a/mutagen/mp3/__init__.py#L38) enum class does not have `__dict__` descriptor as a TypeError. I played around version 1.43 and added `__dict__` descriptor and the error went away. 

I know I can easily create a fork of this repo and maintain that, but I have several questions.

- Would a python 2 update be acceptable? From the documentation, the current release does not support python 2.

- Would this kind of niche one-off fix be accepted? Let's say someone other than myself encounters the same issue when using python 3 in the Google App Engine. 

- The fix I am going to propose is to have __dict__ descriptor to essentially be a no-op function. This should satisfy the fix. However, I can see this being problem from readability and clarity standpoint. Will that be ok?

- In the case that I do maintain a fork, how will we coordinate regression issues and bugs in both codebases?

- For any fixes post-python 2, how should I integrate them back to python 2 in the fork?

I have considered fixing this from the Google App Engine side but since this Google App Engine infrastructure, I am reluctant to approach it that way.

Any discussion on this is appreciated. Sorry for the wall of text. :)

**Comment by lazka** [comment]
As long as the changes are either small or bugfixes I don't mind.

If they are for both Python 2 and 3 they should go to master and I can backport, if Py2 only they should got to the "mutagen-1.43" branch which I just created.

**Comment by mzaman07** [comment]
ok thanks, yes I can focus on it being a python2 fix for now. If python3 is needed then it can be done later.

**Comment by lazka** [comment]
You need to create a PR against that branch.

**Comment by lazka** [comment]
A new Python 2 compatible release is out.
