### ISSUE TITLE
Mutagen is unusable on ZFS

### ISSUE THREAD

**Issue by lovesegfault** [quodlibet/mutagen#478]
When I moved to ZFS I found that [beets](https://github.com/beetbox/beets) became unusably slow, to the point where scrubbing tags in a single FLAC was taking 10 or more **minutes**. I opened an issue, https://github.com/beetbox/beets/issues/3642, to investigate and eventually tracked it down to this portion of mutagen code:
```
 --- modulename: flac, funcname: _writeblock
flac.py(124):         data = bytearray()
flac.py(125):         code = (block.code | 128) if is_last else block.code
flac.py(126):         datum = block.write()
 --- modulename: flac, funcname: write
flac.py(653):         try:
flac.py(654):             return b"\x00" * self.length
flac.py(127):         size = len(datum)
flac.py(128):         if size > cls._MAX_SIZE:
flac.py(138):         assert not size > cls._MAX_SIZE
flac.py(139):         length = struct.pack(">I", size)[-3:]
flac.py(140):         data.append(code)
flac.py(141):         data += length
flac.py(142):         data += datum
flac.py(143):         return data
flac.py(168):         return data
flac.py(868):         data_size = len(data)
flac.py(870):         resize_bytes(filething.fileobj, available, data_size, header)
 --- modulename: _util, funcname: resize_bytes
_util.py(909):     if new_size < old_size:
_util.py(910):         delete_size = old_size - new_size
_util.py(911):         delete_at = offset + new_size
_util.py(912):         delete_bytes(fobj, delete_size, delete_at)
 --- modulename: _util, funcname: delete_bytes
_util.py(875):     if size < 0 or offset < 0:
_util.py(878):     fobj.seek(0, 2)
_util.py(879):     filesize = fobj.tell()
_util.py(880):     movesize = filesize - offset - size
_util.py(882):     if movesize < 0:
_util.py(885):     if mmap is not None:
_util.py(886):         try:
_util.py(887):             mmap_move(fobj, offset, offset + size, movesize)
 --- modulename: _util, funcname: mmap_move
_util.py(704):     assert mmap is not None, "no mmap support"
_util.py(706):     if dest < 0 or src < 0 or count < 0:
_util.py(709):     try:
_util.py(710):         fileno = fileobj.fileno()
_util.py(715):     fileobj.seek(0, 2)
_util.py(716):     filesize = fileobj.tell()
_util.py(717):     length = max(dest, src) + count
_util.py(719):     if length > filesize:
_util.py(722):     offset = ((min(dest, src) // mmap.ALLOCATIONGRANULARITY) *
_util.py(723):               mmap.ALLOCATIONGRANULARITY)
_util.py(722):     offset = ((min(dest, src) // mmap.ALLOCATIONGRANULARITY) *
_util.py(724):     assert dest >= offset
_util.py(725):     assert src >= offset
_util.py(726):     assert offset % mmap.ALLOCATIONGRANULARITY == 0
_util.py(729):     if count == 0:
_util.py(733):     if src == dest:
_util.py(736):     fileobj.flush()
_util.py(737):     file_map = mmap.mmap(fileno, length - offset, offset=offset)
_util.py(738):     try:
_util.py(739):         file_map.move(dest - offset, src - offset, count)
```

On the OpenZFS IRC someone mentioned the issue seems to be the mmap based file writing mutagen is doing. ZFS isn't integrated with the linux cache, and so each mmap operation needs to be copied in and out of the cache making it painfully slow. To test this I applied the following patch to mutagen:
```patch
diff --git a/mutagen/_util.py b/mutagen/_util.py
index 1332f9d..5b9a8cd 100644
--- a/mutagen/_util.py
+++ b/mutagen/_util.py
@@ -20,7 +20,7 @@ import decimal
 from io import BytesIO
 
 try:
-    import mmap
+    mmap = None
 except ImportError:
     # Google App Engine has no mmap:
     #   https://github.com/quodlibet/mutagen/issues/286
@@ -701,8 +701,6 @@ def mmap_move(fileobj, dest, src, count):
         ValueError: In case invalid parameters were given
     """
 
-    assert mmap is not None, "no mmap support"
-
     if dest < 0 or src < 0 or count < 0:
         raise ValueError("Invalid parameters")
 
diff --git a/tests/test__util.py b/tests/test__util.py
index 0ed25ed..55d0d7a 100644
--- a/tests/test__util.py
+++ b/tests/test__util.py
@@ -2,7 +2,7 @@
 
 from mutagen._util import DictMixin, cdata, insert_bytes, delete_bytes, \
     decode_terminated, dict_match, enum, get_size, BitReader, BitReaderError, \
-    resize_bytes, seek_end, mmap_move, verify_fileobj, fileobj_name, \
+    resize_bytes, seek_end, verify_fileobj, fileobj_name, \
     read_full, flags, resize_file, fallback_move, encode_endian, loadfile, \
     intround, verify_filename
 from mutagen._compat import text_type, itervalues, iterkeys, iteritems, PY2, \
@@ -376,33 +376,12 @@ class TMoveMixin(object):
             self.MOVE(o, 0, 1, 2)
             self.MOVE(o, 1, 0, 2)
 
-    def test_larger_than_page_size(self):
-        off = mmap.ALLOCATIONGRANULARITY
-        with self.file(b"f" * off * 2) as o:
-            self.MOVE(o, off, off + 1, off - 1)
-            self.MOVE(o, off + 1, off, off - 1)
-
-        with self.file(b"f" * off * 2 + b"x") as o:
-            self.MOVE(o, off * 2 - 1, off * 2, 1)
-            self.assertEqual(self.read(o)[-3:], b"fxx")
-
 
 class Tfallback_move(TestCase, TMoveMixin):
 
     MOVE = staticmethod(fallback_move)
 
 
-class MmapMove(TestCase, TMoveMixin):
-
-    MOVE = staticmethod(mmap_move)
-
-    def test_stringio(self):
-        self.assertRaises(mmap.error, mmap_move, cBytesIO(), 0, 0, 0)
-
-    def test_no_fileno(self):
-        self.assertRaises(mmap.error, mmap_move, object(), 0, 0, 0)
-
-
 class FileHandling(TestCase):
     def file(self, contents):
         temp = tempfile.TemporaryFile()
```

And the issue immediately went away.

I'd like to request for either:
1. `mutagen` to detect ZFS and disable `mmap`. I don't know if that's possible
2. For consumers of mutagen to be able to specify, somehow, that they _don't_ want to use `mmap`'d files

**Comment by wisp3rwind** [comment]
FWIW, there used to be similar ntfs-3g issues, I don't remember how exactly this got fixed/worked around. The only related issue I managed to find is https://github.com/quodlibet/mutagen/issues/262

**Comment by lazka** [comment]
> FWIW, there used to be similar ntfs-3g issues, I don't remember how exactly this got fixed/worked around. The only related issue I managed to find is #262

It was a kernel bug affecting FUSE based filesystems.

**Comment by lazka** [comment]
> * `mutagen` to detect ZFS and disable `mmap`. I don't know if that's possible

In theory possible (using fstatfs), but I never tried.

> * For consumers of mutagen to be able to specify, somehow, that they _don't_ want to use `mmap`'d files

That will result in you working around the issue and everyone else not knowing about it, so imo not worth it.

Is there an OpenZFS bug report for this issue?

**Comment by lovesegfault** [comment]
> Is there an OpenZFS bug report for this issue?

I don't think so. From the IRC I got the idea that this isn't a _bug_ per-se, more of a negative characteristic of ZFS. The core of the issue, I think, is that ZFS is out-of-tree and so can't be integrated with the kernel cache like "normal" filesystems do. ZFS has it's own cache handling.

**Comment by lazka** [comment]
We read and write every byte in the transaction only once, so I don't see how a missing cache can have any effect. But maybe it's not that simple...

Another "workaround" would be using https://docs.python.org/dev/library/os.html#os.copy_file_range if it exists and prefer that to mmap (but it is Python 3.8 only), but looks like that is missing also: https://github.com/openzfs/zfs/issues/4237

**Comment by lazka** [comment]
@lovesegfault can you try running the following on a ZFS filesystem:

```python
import os
with open("temp.txt", "wb") as h:
    h.write(b"foobar")
with open("temp.txt", "r+b") as h:
    os.copy_file_range(h.fileno(), h.fileno(), 3, 0, 3)
with open("temp.txt", "rb") as h:
    assert h.read() == b'foofoo'
print("OK")
```

**Comment by lovesegfault** [comment]
@lazka That seems to work fine!
```
viins ❯ python -m trace -t ./test.py
 --- modulename: test, funcname: <module>
test.py(1): import os
test.py(2): with open("temp.txt", "wb") as h:
test.py(3):     h.write(b"foobar")
test.py(4): with open("temp.txt", "r+b") as h:
test.py(5):     os.copy_file_range(h.fileno(), h.fileno(), 3, 0, 3)
test.py(6): with open("temp.txt", "rb") as h:
test.py(7):     assert h.read() == b'foofoo'
test.py(8): print("OK")
OK
```
```

**Comment by lazka** [comment]
Thanks for testing. I'll see how this performs compared to mmap and if we can prefer it by default maybe.

**Comment by phw** [comment]
There is some related discussion and analysis about mmap performance at https://tickets.metabrainz.org/browse/PICARD-1878

In this case it is slowing down network file system access. Increasing the buffer size seems to have a big impact.

@lazka could you take a look at the findings there?

**Comment by lazka** [comment]
Thanks, will have a look later. Increasing BUFFER_SIZE sounds good (which I guess is used over SMB when no mmap is available?). The ALLOCATIONGRANULARITY is unrelated, it's only used to decode where to start moving.

**Comment by lazka** [comment]
So mmap is 20x slower on Windows over a loopback network share, while normal reading/writing is about the same. That's surprising. Let's see how things are on Linux next..

**Comment by lazka** [comment]
Not much difference on Linux either. I'll throw out the mmap implementation and increase the buffer size a bit.

**Comment by lovesegfault** [comment]
Thank you @lazka!

**Comment by JamiBradley** [comment]
Thanks for the update!  I was the one that wrote this ticket:  https://tickets.metabrainz.org/browse/PICARD-1878

I was seeing performance issues on local disks as well as network shares.  It seemed to be primarily the reading of the data when not-cached that was the problem.  I was reading from a local disk (E:) in my first tests.  Once the file is cached, performance was never an issue - only the uncached version.

I'll try out the new changes now.

**Comment by lazka** [comment]
> I'll try out the new changes now.

Thanks. Keep in mind that mutagen will only do this expensive operation once per file unless you change the metadata size significantly. Don't confuse this behavior with caching.

**Comment by JamiBradley** [comment]
> Thanks. Keep in mind that mutagen will only do this expensive operation once per file unless you change the metadata size significantly. Don't confuse this behavior with caching. You'd have to add/remove large embedded images to hit this case.

Understood.  My most common use case is when I am adding a new album, so all the new metadata and embedded image is normal for me.

**Comment by lazka** [comment]
A new release is out
