### ISSUE TITLE
mid3v2 Error When Writing Tag with Picture Frame

### ISSUE THREAD

**Issue by anthony-24** [quodlibet/mutagen#479]
I'm using mid3v2 1.3 which uses Mutagen 1.31. I attempted to write MP3 tag with command such as:

```
mid3v2 --song "Song Title" --album "Album Name" --year "2020" --artist "Artist Name" --track "1" --picture "/images/106.jpg" "/mnt/cifs/Radio Programming/Programs/pp212.mp3"
```

However, this produces an error and the tag is not written. The error returned is:

```
mid3v2 [OPTION] [FILE]...
mid3v2: error: no such option: --picture
```
If I leave out the --picture option, the tag is written just fine. Also, it makes no difference if I write the command using the -p option for picture frame.

Kind regards

**Comment by lazka** [comment]
`--picture` was added in mutagen 1.33
