### ISSUE TITLE
cannot catch ID3NoHeaderError

### ISSUE THREAD

**Issue by AlVincentM** [quodlibet/mutagen#481]
I am listing the song titles in a directory and some of the song's metadata are broken. Then I get this error: 
```
  File "/home/vincent/.local/lib/python3.8/site-packages/mutagen/id3/_tags.py", line 67, in __init__
    raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
mutagen.id3._util.ID3NoHeaderError: './Believer.mp3' doesn't start with an ID3 tag
```
I tried catching the errors and skip the broken files but still didn't work:
``` python
from mutagen import MutagenError

try:
    //do something
except (MutagenError, ID3NoHeaderError):
    pass
```

**Comment by lazka** [comment]
What didn't work when you did catch the exception?

**Comment by AlVincentM** [comment]
> What didn't work when you did catch the exception?

Thanks for replying, but I've already fixed it. My syntax was wrong and forgot to update this issue.

**Comment by lazka** [comment]
ok, thanks for the update
