### ISSUE TITLE
Does mutagen support a file-type agnostic abstraction layer?

### ISSUE THREAD

**Issue by jtpavlock** [quodlibet/mutagen#489]
Does mutagen provide a way to abstract the differences between audio formats?

For example, I'd like to say something like:
```python
audio_file = mutagen.File('music.mp3')
audio_file2 = mutagen.File('music.flac')

print(audio_file.artist)
print(audio_file2.artist)
```

Based on [the docs](https://mutagen.readthedocs.io/en/latest/user/gettingstarted.html), it seems like mutagen can return the type of file if unknown ahead of time, but then you still have to import FLAC/ID3 based on what type of file you find? Do I understand that correctly?

**Comment by lazka** [comment]
No, there is https://github.com/beetbox/mediafile though

**Comment by jtpavlock** [comment]
> No, there is https://github.com/beetbox/mediafile as a wrapper though

Is this something you'd be interested in implementing/merging into mutagen?

**Comment by phw** [comment]
There is also #186 for this. Closing this issue to reduce duplicates.
