### ISSUE TITLE
Multiple values being read as one

### ISSUE THREAD

**Issue by Mikhail-Zex** [quodlibet/mutagen#492]
When I try to add multiple album artists or genres, by passing a List to mutagen, the values are embeded just right but later almost every single music player I've tried reads the tags like: `album artist: Aiobahn/Rionos/Stephen Walkig` and much worse off, `genre: nordic music/scorecore/epicore/game music` instead of reading each as separate values.

I'm not attaching the related code here (sorry), I'm working on spotDL, you can run [this](https://github.com/Mikhail-Zex/spotify-downloader/blob/reStructure/reCode/Temp/__main__.py) file to replicate the problem, in case you don't find it, look up commit **406bfdb2f9b8dc9d70a237b2e57ba743559f337e**

I'm not sure if I'm doing something wrong or using the wrong music players but any assistance is greatly appreciated.

I have tried Groove Music Player, Google Play Music, Music Bee, AIMP and VLC

**Comment by lazka** [comment]
Which tagging format are we talking about here?

**Comment by Mikhail-Zex** [comment]
ID3 V2.3 (on windows)

**Comment by ben-xo** [comment]
Yes, same here. I'm on MacOS but I don't think that's relevant. They're mp3 files.

**Comment by lazka** [comment]
id3v2.3 doesn't support multiple values, you'd need to save as v2.4 to preserve the list

**Comment by Mikhail-Zex** [comment]
essentially there is no way i can get multiple artists on windows ?

**Comment by lazka** [comment]
You can use id3v2.4, which it seems is supported by later versions of Windows 10

**Comment by Mikhail-Zex** [comment]
Ok. Tq for the info.

**Comment by Mikhail-Zex** [comment]
Hey @lazka , it's me again. I'm now three maintainer on spotify-downloader. One of the projects we're undertaking is proton. A gui framework built on cefpython3 (just like all Adobe apps, vs code and everything else electronjs). I have a lot of ideas but no html/css/js/dom knowledge. 

Since you guys also deal with gui's. I believe that we could help you make much better looking gui's overnight. If you know anyone who can write good webpage and stuff, v could you put us in touch? Please?
