### ISSUE TITLE
Windows 7 fails to view tags of ID3v2.3 after modified by mutagen

### ISSUE THREAD

**Issue by LittleYe233** [quodlibet/mutagen#501]
(Well there are so many issues that I am not able to find if there exist some issues that meet my needs, so I submit this one.)

I use mutagen on Windows 7 to modify some tags of MP3 files with ID3v2.3. However after modifying them, Windows cannot recognize their tags. I used the code below ("1.mp3" is the modified file by mutagen, "2.mp3" is modified by Windows built-in methods.)

```python
In [1]: import mutagen

In [2]: from mutagen.id3 import ID3, APIC, TIT2, TPE1, TALB

In [3]: mutagen.version
Out[3]: (1, 45, 1)

In [4]: mp3 = ID3('1.mp3')

In [5]: mp3.keys()
Out[5]: dict_keys(['TSSE', 'COMM::XXX', 'TALB', 'TIT2', 'TPE1', 'TPOS', 'TRCK'
'APIC:', 'COMM:ID3v1 Comment:eng'])

In [6]: mp3['TALB'], mp3['TIT2'], mp3['TPE1']
Out[6]:
(TALB(encoding=<Encoding.UTF16: 1>, text=['Shooting Snow 2012']),
 TIT2(encoding=<Encoding.UTF16: 1>, text=['雪恋少女']),
 TPE1(encoding=<Encoding.UTF16: 1>, text=['みぃしゃ']))

In [7]: mp3.version
Out[7]: (2, 3, 0)

In [11]: mp3['TIT2'] = TIT2(encoding=1, text='雪恋少女 - みぃしゃ')

In [12]: mp3.save()

In [13]: mp3.version
Out[13]: (2, 3, 0)

In [14]: mp3['TALB'], mp3['TIT2'], mp3['TPE1']
Out[14]:
(TALB(encoding=<Encoding.UTF16: 1>, text=['Shooting Snow 2012']),
 TIT2(encoding=<Encoding.UTF16: 1>, text=['雪恋少女 - みぃしゃ']),
 TPE1(encoding=<Encoding.UTF16: 1>, text=['みぃしゃ']))
```

And the pictures of the result are below (click these images can be redirected to the mirror site):

Picture A: the original status of tags of "1.mp3" in Windows view.

[![Picture A](https://s1.ax1x.com/2020/10/25/BnSYUP.png)](https://imgchr.com/i/BnSYUP)

Picture B: the original status of tags of "1.mp3" and "2.mp3" in Mp3tag view.

[![Picture B](https://s1.ax1x.com/2020/10/25/BnSa8S.png)](https://imgchr.com/i/BnSa8S)

Picture C: the current status of modified tags of "1.mp3" in Windows view. The tags cannot be seen now.

[![Picture C](https://s1.ax1x.com/2020/10/25/BnSt4f.png)](https://imgchr.com/i/BnSt4f)

Picture D: the current status of modified tags of "1.mp3" and not-modified tags of "2.mp3" in Mp3tag view. The modified tags can be displayed well.

[![Picture D](https://s1.ax1x.com/2020/10/25/BnSUC8.png)](https://imgchr.com/i/BnSUC8)

**Comment by lazka** [comment]
You need to use `save(v2_version=3)`, otherwise mutagen will save using id3v2.4 and Windows 7 doesn't support that.

**Comment by LittleYe233** [comment]
> You need to use `save(v2_version=3)`, otherwise mutagen will save using id3v2.4 and Windows 7 doesn't support that.

Thanks for your reply. But when I just used `save()`, it can also be parsed as ID3v2.3. What is the principle here?

**Comment by lazka** [comment]
in case you mean the 'version' attribute, that shows the version the parsed file had initially and save() does't change its value.

btw, I think Windows 10 can read id3v2.4 tags now

**Comment by LittleYe233** [comment]
> in case you mean the 'version' attribute, that shows the version the parsed file had initially and save() does't change its value.
> 
> btw, I think Windows 10 can read id3v2.4 tags now

Ah, that works. Thank you for your help again! :)
