### ISSUE TITLE
Is it possible to get ID3 meta "disc_total"  ?

### ISSUE THREAD

**Issue by qiulang** [quodlibet/mutagen#519]
In iTune, it shows as disc number, e.g.
<img width="586" alt="Window_and_Song_Info" src="https://user-images.githubusercontent.com/516243/112951178-a9226b00-916d-11eb-9761-b10da1413b86.png">

In https://github.com/devsnd/tinytag it is called `tag.disc_total    # the total number of discs`

But I can't find this data in metagen or I just miss it?

Thanks!

**Comment by phw** [comment]
In ID3 this information is stored in the TPOS frame in the format 1/3 (first number is the current disc number, the second the total number of discs).

**Comment by qiulang** [comment]
Hi can you show me sample codes to read this ? 
Thanks a lot!

**Comment by philippedostert** [comment]
```
import mutagen.id3
id3_data = mutagen.id3.ID3('yourfile.mp3')
tpos = id3_data['TPOS'].text[0].split('/')  # ['1', '1']
```

**Comment by qiulang** [comment]
thanks
