### ISSUE TITLE
Error while loading flac file data from an io.BytesIO object: file said 4 bytes, read 0 bytes

### ISSUE THREAD

**Issue by nukemiko** [quodlibet/mutagen#522]
Error message outputs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mutagen/flac.py", line 848, in save
    self._save(filething, self.metadata_blocks, deleteid3, padding)
  File "/usr/lib/python3.9/site-packages/mutagen/flac.py", line 852, in _save
    header = self.__check_header(f, filething.name)
  File "/usr/lib/python3.9/site-packages/mutagen/flac.py", line 909, in __check_header
    header = fileobj.read(4)
  File "/usr/lib/python3.9/site-packages/mutagen/flac.py", line 69, in read
    raise error("file said %d bytes, read %d bytes" % (
mutagen.flac.error: file said 4 bytes, read 0 bytes
```
While you try to use flac.FLAC load data from an io.BytesIO object.
Related code:
```
from mutagen import flac
from io import BytesIO
raw = BytesIO(open('/home/menacing/Music/Private/404 not found.flac','rb').read())
flacobj = flac.FLAC(fileobj=raw)
newBytesIOobj = BytesIO()
flacobj.save(newBytesIOobj)
```
But for the same operates, if switch to a mp3 file and use mp3.MP3 load data from the io.BytesIO object, it's no error.

**Comment by lazka** [comment]
You can only save back to a valid flac file/BytesIO.

**Comment by nukemiko** [comment]
> You can only save back to a valid flac file/BytesIO.

I confirmed `'/home/menacing/Music/Private/404 not found.flac'` is a valid flac file, and contents of BytesIO object `raw` are from `open('/home/menacing/Music/Private/404 not found.flac','rb').read()`. Then I executed `flacobj = flac.FLAC(fileobj=raw)`.
But I can't use `flacobj.save()` save data to anywhere.
`flacobj.save(fileobj=raw)` -> `mutagen.flac.error: file said 4 bytes, read 0 bytes`
`flacobj.save()` -> `TypeError: Missing filename or fileobj argument`
`flacobj.save(fileobj=newBytesIOobj)` -> `mutagen.flac.error: file said 4 bytes, read 0 bytes`
`flacobj.save(filename='new.flac')`(`new.flac` is an existing flac file) -> `mutagen.flac.error: file said 4 bytes, read 0 bytes`
`flacobj.save(fileobj=open('new.flac','wb+'))` -> `mutagen.flac.error: file said 4 bytes, read 0 bytes`

**Comment by lazka** [comment]
This indicates that both newBytesIOobj and new.flac are empty and not valid flac files.

**Comment by nukemiko** [comment]
> This indicates that both newBytesIOobj and new.flac are empty and not valid flac files.

I found the solution. Just create two io.BytesIO objects from a same valid flac file.
```
from mutagen import flac
from io import BytesIO
with open('404 not found.flac','rb') as con:
    rawcon = con.read()
obj1 = BytesIO(rawcon)
obj2 = BytesIO(rawcon)
flacobj = flac.FLAC(obj1)
<...some operations...>
flacobj.save(obj2)
```
No error occurred.
