### ISSUE TITLE
install mutagen 1.21 in python 3.8

### ISSUE THREAD

**Issue by 2sahil3** [quodlibet/mutagen#528]
I tried to install audiodiff by 'pip install audiodiff'
but at some point it throwed me following error :
ERROR: Could not find a version that satisfies the requirement mutagen==1.21 (from versions: 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.25.1, 1.26,
 1.27, 1.28, 1.29, 1.30, 1.31, 1.32, 1.33, 1.33.1, 1.33.2, 1.34, 1.34.1, 1.35, 1.35.1, 1.36, 1.36.1, 1.36.2, 1.36.3, 1.37, 1.38, 1.39, 1.40.0, 1.41.0, 1.41.1, 1.42.0,
 1.43.0, 1.43.1, 1.44.0, 1.45.0, 1.45.1)
ERROR: No matching distribution found for mutagen==1.21

I upgraded pip, installed mutagen 1.45.1 but then too its showing the same.

**Comment by lazka** [comment]
mutagen 1.21 is 8 years old and Python 2 only.

**Comment by lazka** [comment]
audiodiff seems to be a Python 2 package, so you need use Python 2 to install it.

**Comment by 2sahil3** [comment]
But do python 3 modules work in python 2?
if no then i must find another way out for my project !!!

**Comment by lazka** [comment]
they dont.

**Comment by 2sahil3** [comment]
Ok, thanks for the reply.

**Comment by lazka** [comment]
maybe this provides what you need? https://github.com/beetbox/audioread

**Comment by 2sahil3** [comment]
Cool, thanks!
