### ISSUE TITLE
cant tag wav

### ISSUE THREAD

**Issue by riegerben** [quodlibet/mutagen#549]
hi, im trying to tag a wav file.
the tags are saved but i cant see them in the file without using mutagen.

example code:

import mutagen.wave
from mutagen.id3 import ID3, TIT2, TALB, TPE1

f = mutagen.wave.WAVE("example_wav.wav")

f.tags.add(TALB(encoding=0, text=['some_album']))
f.tags.add(TIT2(encoding=0, text=['some_title']))
f.tags.add(TPE1(encoding=0, text=['some_artist']))

f.save()

**Comment by sparr** [comment]
What other tool(s) are you using that can't see them?

**Comment by phw** [comment]
WAVE files don't really have a proper tagging standard, Mutagen currently supports writing ID3 tags to WAVE files. This is not supported by all software. If you want to verify your tags are there try loading the file with foobar2000.

Windows and other Microsoft products can only read tags stored as RIFF INFO tags inside the WAVE file. INFO tags are a rather limited tagging format and currently not supported by mutagen. See #207
