### ISSUE TITLE
WXXX URL string should not end with a NULL-terminated character

### ISSUE THREAD

**Issue by hlecnt** [quodlibet/mutagen#555]
Hi,

I noticed that Apple AVPlayer is not able to decode the WXXX tag generated by mutagen while it's fine on Google Chrome.
After some investigations I found that the issue comes from the NULL-terminated character added to the URL string passed to WXXX().

I found an online HLS stream (radio) that confirms that:
[https://www.maxradio.ca/UHD/Maxv1/Max.m3u8](https://www.maxradio.ca/UHD/Maxv1/Max.m3u8)

If you dump the binary of one .aac file, you'll see multiple WXXX tags. 
```
000000d0: 7200 5758 5858 0000 0040 0000 0361 7274  r.WXXX...@...art
000000e0: 776f 726b 5552 4c5f 3634 3078 0068 7474  workURL_640x.htt
000000f0: 7073 3a2f 2f77 7777 2e6d 6178 7261 6469  ps://www.maxradi
00000100: 6f2e 6361 2f69 6d61 6765 732f 4d61 7852  o.ca/images/MaxR
00000110: 6164 696f 5f34 3030 2e70 6e67 5758 5858  adio_400.pngWXXX
00000120: 0000 0041 0000 0361 7274 776f 726b 5552  ...A...artworkUR
00000130: 4c5f 3132 3830 7800 6874 7470 733a 2f2f  L_1280x.https://
00000140: 7777 772e 6d61 7872 6164 696f 2e63 612f  www.maxradio.ca/
00000150: 696d 6167 6573 2f4d 6178 5261 6469 6f5f  images/MaxRadio_
00000160: 3630 302e 706e 6757 5858 5800 0000 4100  600.pngWXXX...A.
00000170: 0003 6172 7477 6f72 6b55 524c 5f31 3932  ..artworkURL_192
00000180: 3078 0068 7474 7073 3a2f 2f77 7777 2e6d  0x.https://www.m
00000190: 6178 7261 6469 6f2e 6361 2f69 6d61 6765  axradio.ca/image
000001a0: 732f 4d61 7852 6164 696f 5f38 3030 2e70  s/MaxRadio_800.p
000001b0: 6e67 5446 4c54 0000 0009 0000 034d 5047  ngTFLT.......MPG
```

Tags haven't any NULL-terminated character at the end of the URL.

I was able to fix the issue by removing this NULL-terminated character when writing the tag binary.

You will find a PR for that here: [https://github.com/quodlibet/mutagen/pull/554](https://github.com/quodlibet/mutagen/pull/554)

Does anybody already faced this kind of issue ?

Regards,

**Comment by hlecnt** [comment]
In addition, I faced the same issue with the TXXXX tag.

**Comment by lazka** [comment]
huh, but TXXX requires termination for multiple values. And I remember that iTunes always terminates there.

Can you maybe try using id3v2.3 to rule out any differences there? Maybe the parser you are using isn't fully 2.4 compatible: `audio.save(v2_version=3)`

**Comment by hlecnt** [comment]
The issue is seen only on Apple devices (MacOS and iOS) using AVPlayer from Apple (native in Safari). Unfortunately I don't have access to the parser.

You mentioned TagLib, I took a look to the `ByteVector TextIdentificationFrame::renderFields() const`. From my undestanding the produced frame does not end with a NULL-termination character. This character is used to separate strings in case of multi-strings, as you said. 

I played with the `tagwriter` example tool too by adding title, artist and custom TXXX. And these frames are not ended by a NULL-termination character.

Maybe the issue on Apple device is due to this leading NULL-termination character that indicates a list separator without a next element in this list => the list is broken, the frame is ignored by the parser.

I'll let you inform about the test with `audio.save(v2_version=3`

**Comment by hlecnt** [comment]
Hello, I have some news about my issue.

I've tried TXXX with `audio.save(v2_version=3)` and now the TXXX frame is decoded by AV player (Apple). I also tried WXXX frame with `audio.save(v2_version=3)` but unfortunately it's not decoded by AV player.

When using `audio.save(v2_version=3)` and UTF-8, a NULL-termination (`\0`) character is added after each character... The final size of the frame is twice the size of the text to encode. But these NULL-termination characters are not present if the encoding is LATIN1. This is weird as the characters used in the text to encode are ASCII characters having the same hex value in both LATIN1 and UTF-8.

I just wrote a simple code to compare the binaries generated by mutagen:
``` python
from mutagen.id3 import ID3, TXXX, Encoding, PictureType
from email.utils import formatdate
import time
import io
import base64

id3 = ID3()
id3.add(TXXX(encoding=Encoding.UTF8, desc="description", text="http://www.google.fr/"))

def no_padding(*args):
  """This removes all padding in all cases"""
  return 0

for version in range(3,5):
  for encoding in [ Encoding.LATIN1, Encoding.UTF8]:
    id3 = ID3()
    id3.add(TXXX(encoding=encoding, desc="description", text="http://www.google.fr/"))
    inmemory_file = io.BytesIO()
    id3.save(inmemory_file, padding=no_padding, v2_version=version)
    print(f"v2.{version} {encoding!s: >20}:  {inmemory_file.getvalue()}")

```

And the output is:
```
v2.3      Encoding.LATIN1:  b'ID3\x03\x00\x00\x00\x00\x00-TXXX\x00\x00\x00#\x00\x00\x00description\[x00http://www.google.fr/\x00]()'
v2.3        Encoding.UTF8:  b'ID3\x03\x00\x00\x00\x00\x00STXXX\x00\x00\x00I\x00\x00\x01\xff\xfed\x00e\x00s\x00c\x00r\x00i\x00p\x00t\x00i\x00o\x00n\x00\x00\x00\xff\xfeh\x00t\x00t\x00p\x00:\x00/\x00/\x00w\x00w\x00w\x00.\x00g\x00o\x00o\x00g\x00l\x00e\x00.\x00f\x00r\x00/\x00\x00\x00'
v2.4      Encoding.LATIN1:  b'ID3\x04\x00\x00\x00\x00\x00-TXXX\x00\x00\x00#\x00\x00\x00description\[x00http://www.google.fr/\x00]()'
v2.4        Encoding.UTF8:  b'ID3\x04\x00\x00\x00\x00\x00-TXXX\x00\x00\x00#\x00\x00\x03description\[x00http://www.google.fr/\x00]()'
```

Only UTF-8 encoding in v2.3 adds NULL-termination characters after each character. 

Do you know why UTF-8 strings are encoded like this in v2.3 ?

Thanks

**Comment by phw** [comment]
> Only UTF-8 encoding in v2.3 adds NULL-termination characters after each character.

UTF-8 is not supported for ID3v2.3, hence this is not UTF-8 but UTF-16. Each character takes at least 2 bytes, the null characters you see there are no termination but simply the second byte of a character.

**Comment by hlecnt** [comment]
The expected behavior for WXXX and TXXX in 2.4 is not clear. `taglib` does not add a NULL-termination character after the last string in WXXX or TXXX frames. This behavior fixes my issue. 
This issue seems to be specific to some MacOS+Safari versions => Closing the issue
