### ISSUE TITLE
is mutagen under GPL-2.0-only or GPL-2.0-or-later

### ISSUE THREAD

**Issue by MrRawes** [quodlibet/mutagen#560]
[GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only)
or
[GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html)

**Comment by lazka** [comment]
https://github.com/quodlibet/mutagen/blob/master/setup.py#L277

**Comment by MrRawes** [comment]
thanks
