### ISSUE TITLE
wav file bps incorrectly identified as absurdly high value

### ISSUE THREAD

**Issue by sparr** [quodlibet/mutagen#578]
mplayer and vlc both correctly identify this wav file as 0.3 seconds long. vlc says it has 4 bits per sample, which seems low. mutagen, on the other hand, says it's 1558410 bps and 0.00 seconds long. I have a few hundred other wav files from the same source with similar behavior, some signficantly longer than this one.

[short_wav_file.zip](https://github.com/quodlibet/mutagen/files/9544707/short_wav_file.zip)

The file is an audio sample from the game One Finger Death Punch.

**Comment by phw** [comment]
This has already been fixed in https://github.com/quodlibet/mutagen/pull/566

**Comment by phw** [comment]
@lazka Any plans for a new release?

**Comment by lazka** [comment]
> @lazka Any plans for a new release?

done

if you want access/publish rights for github/pypi, let me know
