### ISSUE TITLE
Unclear what the build system is

### ISSUE THREAD

**Issue by mgorny** [quodlibet/mutagen#581]
What is the actual build system used by mutagen?

`pyproject.toml` has some poetry metadata but the `build-system` section includes setuptools requirements. However, even then it doesn't declare any `build-backend`, neither setuptools' nor poetry's.

**Comment by lazka** [comment]
https://peps.python.org/pep-0517/

> If the pyproject.toml file is absent, or the build-backend key is missing, the source tree is not using this specification, and tools should revert to the legacy behaviour of running setup.py (either directly, or by implicitly invoking the setuptools.build_meta:__legacy__ backend).

Is this causing any problems? I can make it explicit if needed

**Comment by lazka** [comment]
See #582.

I'd still like to know if this is causing any problems and requires a new release.

**Comment by lazka** [comment]
(as for the poetry/setuptools mix.. it allows me to use poetry for dev, while still providing a setup.py with some minimal metadata duplication)
