### ISSUE TITLE
album metadata is not being written to when using EasyID3

### ISSUE THREAD

**Issue by maximumpeaches** [quodlibet/mutagen#615]
When I use EasyID3 to write the title, author, album, and track number, everything works fine except the album. I described my problem in [this stackoverflow question](https://stackoverflow.com/questions/76497869/mutagen-easyid3-adds-metadata-except-the-album-name). Please let me know if any additional info would be useful to debug this.

**Comment by phw** [comment]
The tags added look good. It also works for me. What does mutagen-inspect show for the file?

**Comment by maximumpeaches** [comment]
```text
$ mutagen-inspect 14ch12.mp3
-- 14ch12.mp3
- MPEG 2 layer 3, 32000 bps (CBR?), 24000 Hz, 1 chn, 3033.82 seconds (audio/mp3)
TALB=BSRS
TIT2=Chapter 12
TOLY=Google
TPE1=Google
TRCK=15
```

**Comment by phw** [comment]
Sorry for not getting back to this earlier. But this all looks good, the `TALB` frame is what holds the album title. It's probably best to ask the VLC team about this. Also maybe it is a VLC version thing. As I wrote before it works for me (VLC 3.018 on Ubuntu).

**Comment by phw** [comment]
Closing as there was no further discussion and the metadata is as expected with TALB being set.
