### ISSUE TITLE
AcoustID Fingerprint

### ISSUE THREAD

**Issue by kkarkos** [quodlibet/mutagen#635]
Hi there, I'm using mutagen to tag WAV files with ID3 tags. The tagging is working fine, beside an AcoustID Fingerprint is being added automatically for every file. I can't find any documentation about that. Is this a bug?

**Comment by phw** [comment]
No, mutagen does not write any tags by itself. Either your code sets this tag or the tag was already present before. In any way the value needs to come from somewhere. Did you run some AcoustID fingerprinting on the files? If yes, with which tool?

What exactly does your mutagen code do?

**Comment by kkarkos** [comment]
I just found the issue. My source file had the TXXX:Acoustid Fingerprint already in it. I'm cross-comparing my files with different DAWS, Apps and Software after adding tags. One of them must have added it! 🤦‍♂️
