### ISSUE TITLE
Lame VBR Preset

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#66]
Originally reported by: **Christoph Reiter (Bitbucket: [lazka](http://bitbucket.org/lazka), GitHub: [lazka](http://github.com/lazka))**

---

_From [Ph0X...@gmail.com](https://code.google.com/u/104933050515893723179/) on June 03, 2010 23:04:55_

```
I've gone through all python libraries, and even other programs and 
libraries, but I can't find anything that can figure out the VBR preset 
used by LAME on an mp3.

The only program I know of that does it is Mr. QuestionMan http://www.burrrn.net/?page_id=5 And it works very well, but I want to make renaming scripts and stuff that 
would need to parse mp3s and find that information. Sadly, I can't find any 
way of doing this.

It would be really great if you guys could implement it. Not sure why no 
one has made anything similar. If they can do it, I'm guessing it's 
possible? Unless they guess it according to the average bitrate, but I 
personally doubt that.

And I'm speaking about v0-v9 setting, of course.
```

_Original issue: http://code.google.com/p/mutagen/issues/detail?id=66_

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/66

**Comment by lazka** [comment]
test vector on bitbucket, so it doesn't get lost: https://bitbucket.org/lazka/quodlibet/downloads/lame-test-vector.tar.xz

The beets issue, which was never directly referenced here afaics: https://github.com/beetbox/beets/issues/116

Closing this. If anyone has a use case/interface proposal to expose more, please bring it up here.

**Comment by lengtche** [comment]
I don't know if you can and/or want to comment on the referenced issue above?

My use case is that when using beets, it would be nice to be able to query my library for specific VBR quality. Looking at the average bitrate of a file, it rarely seems to match what the LAME targets propose from [here](http://wiki.hydrogenaud.io/index.php?title=LAME).

Right now I just have a barebones version of parts of dnuos that I converted to Python 3 in order to get the LAME codec profile.

**Comment by lazka** [comment]
Do you indent to use the extracted quality somehow or do you just want to know it?

**Comment by sampsyo** [comment]
@lengtche, I notice that `LAMEHeader` already has a `preset_used` field. Does that contain what you need?

**Comment by lengtche** [comment]
@lazka It's for a) display purposes on my folder names and b) querying in beets with `beets ls -a albumquality:v0`. I think I remember seeing a commit in this repo where the information was exposed, but I can't find it anymore.

@sampsyo Think I remember `preset_used` only returned whether it was VBR or not. It's been a few weeks since I checked.

**Comment by lengtche** [comment]
I see class `LAMEHeader` that @sampsyo is mentioning. Searching the repository only seems to indicate that it's not yet available for consumption. In this class there's property [`vbr_quality`](https://github.com/quodlibet/mutagen/blob/a5d082edb76bffd529c0cb93b892c73268b72cd5/mutagen/mp3/_util.py#L36), which looks like what I want.

**Comment by sampsyo** [comment]
Indeed! I did a little poking, and it's possible to construct the right object:

```py
>>> mf = mutagen.File(fn)
>>> offset = mutagen.mp3._util.XingHeader.get_offset(mf.info)
>>> f = open(fn)
>>> f.seek(mf.info.frame_offset + offset, 0)
>>> xh = mutagen.mp3._util.XingHeader(f)
>>> xh.lame_header.vbr_quality
0
>>> xh.lame_header.stereo_mode
3
```

That does require opening the file again, though. Maybe the `MPEGFrame` object should keep around the `XingHeader` that's parsed, if any.

**Comment by lazka** [comment]
What about

```python
mutagen.mp3.MPEGInfo.encoder_settings
"""text: a guess about the settings used for encoding, e.g. "-V0" for LAME.
Values might change in the future, use for display purposes only.
"""
```

**Comment by lengtche** [comment]
@sampsyo Thank you. I tried tinkering with `_util` before but didn't figure it out. What's `fn`?

@lazka That would work. I assume it wouldn't simply return the id3v2's `TSSE` heading, right?

**Comment by sampsyo** [comment]
`fn` is just a filename.

**Comment by lazka** [comment]
@lengtche yes

**Comment by lazka** [comment]
Here is what I get with the dnuos logic: https://bpaste.net/show/a730d569e9fd

a bit hit and miss

**Comment by lazka** [comment]
This is in master now: https://bpaste.net/show/d1bfd13f0ae1

Any thoughts?

**Comment by sampsyo** [comment]
Wow; that looks quite accurate! Nice work on the heuristic. Does this look useful for your purposes, @lengtche?

**Comment by lengtche** [comment]
Oh, woah! This is fantastic.

That is _exactly_ what I was looking for.

Much appreciated.

**Comment by lazka** [comment]
Ok.
