### ISSUE TITLE
should be able to write ID3v2.3 tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#82]
Originally reported by: **Christoph Reiter (Bitbucket: [lazka](http://bitbucket.org/lazka), GitHub: [lazka](http://github.com/lazka))**

---

_From [e...@anentropic.com](https://code.google.com/u/105664610503131094268/) on January 26, 2011 14:07:31_

```
some references for below about Windows and v2.4 tags http://en.wikipedia.org/wiki/ID3#ID3v2 http://blogs.cs.st-andrews.ac.uk/stuart/2010/01/26/windows-7-and-id3-2-4/ http://forum.dbpoweramp.com/showthread.php?p=92466 and: http://www.id3.org/ "the most popular version implemented today is ID3 version 2.3. A
follow on version, 2.4, is documented on this website but has not
achieved popular status due to some disagreements on some of the
revisions and the tremendous inertia present in the software and
hardware marketplace"

It seems like being able to read v2.4 is great but v2.3 tags should be
written by default. I had a quick look in the src hoping there would be an easy hack for Mutagen to output v2.3 tags but I didn't find a way yet.
```

_Original issue: http://code.google.com/p/mutagen/issues/detail?id=82_

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/82

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/85

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/160

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/2041

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/403
