### ISSUE TITLE
Add support for writing ID3v2.3 tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#85]
Originally reported by: **Christoph Reiter (Bitbucket: [lazka](http://bitbucket.org/lazka), GitHub: [lazka](http://github.com/lazka))**

---

_From [lalinsky](https://code.google.com/u/lalinsky/) on March 29, 2011 16:43:44_

```
Mutagen always supported only saving of ID3v2.4 tags. When I considered using it in Picard, I implemented ID3v2.3 support by subclassing the ID3 class. I'd like to get this code included in Mutagen, so that we do not have to watch Mutagen for changes that could possibly make it incompatible. The code has been in use for a couple of years now (and since the majority of Picard uses are on Windows, they basically have to use ID3v2.3), so I'm pretty confident it's safe.
```

**Attachment:** [id3v23.diff](http://code.google.com/p/mutagen/issues/detail?id=85)

_Original issue: http://code.google.com/p/mutagen/issues/detail?id=85_

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/85

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/82

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/160

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/2041

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/403

**Comment by svnpenn** [comment]
@lazka if this is fixed in mutagen - can it be brought into quodlibet?
